### ISSUE TITLE
Namco 163 audio: Wave Length is limited to 32 samples

### ISSUE THREAD

**Issue by infval** [TASVideos/fceux#105]
Found here: http://www.romhacking.net/forum/index.php?topic=21907.msg306903#msg306903

https://wiki.nesdev.com/w/index.php/Namco_163_audio:

> Sound RAM $7C - High Frequency and Wave Length
> the waveform length = 256 - %LLLLLL00 samples

[Mesen](https://github.com/SourMesen/Mesen/blob/cda0a0bdcb5525480784f4b8c71de6fc7273b570/Core/Namco163Audio.h#L61):
`256 - (_internalRam[baseAddr + SoundReg::WaveLength] & 0xFC)`

[FCEUX](https://github.com/TASVideos/fceux/blob/5be92d3ee50fcdc04ec4d727cef5201fa8fba378/src/boards/n106.cpp#L160):
`LengthCache[w] = (8 - ((V >> 2) & 7)) << 2;`

Fix:
`LengthCache[w] = 256 - (V & 0xFC);`

Audio comparison: [Final_Lap_(J)_Namco_163_FCEUX_Test.zip](https://github.com/TASVideos/fceux/files/4458256/Final_Lap_.J._Namco_163_FCEUX_Test.zip)

**Comment by g0me3** [comment]
fixed in 5d872472efdf6e13b7b3cdc2cf71f225269adb42
