### ISSUE TITLE
APU square issue

### ISSUE THREAD

**Issue by eugene-s-nesdev** [TASVideos/fceux#11]
R.C. Pro-Am II (U) [!].nes
```
CRC32: 03DB5562
MD5: F6277E4231D802A928BB72C1DADAD6FC
SHA-1: 8C68582BDAA32FBC8C7CD858991D4E00D3B1569C
```
Square 1 channel has wrong sound during game title

**Comment by dragon2snow** [comment]
try cpu ram fill ff

**Comment by bbbradsmith** [comment]
That doesn't appear to affect it, @dragon2snow.

**Comment by dragon2snow** [comment]
oh，

**Comment by eugene-s-nesdev** [comment]
even FCEUX 2.2.2 (with no RAM init option) has this bug:
[R.C. Pro-Am II (U) [FCEUX].zip](https://github.com/TASVideos/fceux/files/2119477/R.C.Pro-Am.II.U.FCEUX.zip)

**Comment by retro-wertz** [comment]
If i understand correctly, when sweep unit is muting the channel, the current period should remain unchanged. Removing curfreq[P]=0; fixes this without causing square-channel related issues to a few common titles i have tested.

```
diff --git a/src/sound.cpp b/src/sound.cpp
index 7390cce8..7acd4273 100644
--- a/src/sound.cpp
+++ b/src/sound.cpp
@@ -443,7 +443,7 @@ static void FrameSoundStuff(int V)
       if((mod+curfreq[P])&0x800)
       {
        sweepon[P]=0;
-       curfreq[P]=0;
+       //curfreq[P]=0;
       }
       else
       {

```

**Comment by g0me3** [comment]
looks legit, let's try it and reopen the issue if someone prove this is wrong...
