### ISSUE TITLE
Artifacts link doesn't work with multiple appveyor jobs

### ISSUE THREAD

**Issue by bbbradsmith** [TASVideos/fceux#115]
The "interim" download link on the fceux.com website links to a build from 2017, and also links to the sourceforge SVN instead of here.

I tried updating download.html with 914a22383b97ec37ea5dfa2fc309efa8b0dc5010 but I dunno if that's actually connected to the website or not?

**Comment by zeromus** [comment]
i pushed the latest web docs to the webserver

**Comment by bbbradsmith** [comment]
LOL of course since I posted this the appveyor has grown a second job and now that artifacts link doesn't work anymore (╯°Д°)╯︵┻━┻

I'm not sure appveyor will even allow a generic link to the latest artifact like that unless there is only a single job. I could get two Windows builds into a single job possibly, but I have no idea to get that Ubuntu build which needs a separate image into that same job. :(

Not sure what to do about it. Currently looking into appveyor to see if there's a way. (Going to repoen the issue to keep track of it for myself.)

**Comment by zeromus** [comment]
FYI, I have rigged things so fceux.com bounces to http://tasvideos.github.io/fceux/
so now when anyone updates docs it will go live immediately.
I will continue to mess around with the redirection so that hopefully old deep links get redirected too, but I need to wait for some stuff to reconfigure and propagate

**Comment by zeromus** [comment]
and by the way, I had desmume windows x86 and x64 builds both working on appveyor for a long time, as two artifacts. only within the past few months did I nuke the x86 one.

**Comment by bbbradsmith** [comment]
Okay, figured out how to make a URL that links to the current artifact. I don't think there's a nice page that'll show the 3 artifacts, but at least individual latest binary can be linked like this:
```
https://ci.appveyor.com/api/projects/zeromus/fceux/artifacts/fceux.zip?branch=master&job=Image%3A%20Visual%20Studio%202019
```

Still trying to figure out if I can rename the job from "Image: Visual Studio 2019" to something more friendly like "Windows"...

**Comment by bbbradsmith** [comment]
Alright, got the jobs named more nicely and added links to all 3 builds in #123
