### ISSUE TITLE
FCEUX64's GUI looks like Win98 style.

### ISSUE THREAD

**Issue by Yave-Yu** [TASVideos/fceux#125]
Why it's not in modern flat style?
![FCEUX64Win98Style](https://user-images.githubusercontent.com/54294476/84964655-3ba5d080-b13f-11ea-939a-759ea38078e4.png)

**Comment by bbbradsmith** [comment]
That's an interesting one. Not much of a functional problem, really, but I have no idea how to fix it either. Something to do with manifest files maybe? The microsoft documentation about that is an unreadable mess. :(

**Comment by bbbradsmith** [comment]
Should be fixed with #126
