### ISSUE TITLE
WIN10 gui problems

### ISSUE THREAD

**Issue by g0me3** [TASVideos/fceux#145]
number input window for windows port sometimes looks wrong.
normally it looks like this https://i.imgur.com/qka0pww.png
but for my desktop theme it looks like this https://www.dropbox.com/s/2u6lhz6n59mxazg/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202020-08-03%2011.19.59.png?dl=0

**Comment by zeromus** [comment]
this is always going to look wrong due to the lazy way it's programmed, but at least I can make it not be cut off
