### ISSUE TITLE
[Feature Request] Git Version

### ISSUE THREAD

**Issue by Amnesia1000** [TASVideos/fceux#152]
It would be nice to add the git version to the title window and "About", for better control.
For example "FCEUX 2.2.3 adf9834" or "FCEUX 2.2.3 r245"

**Comment by zeromus** [comment]
stop writing issues without writing what frontend you're referring to

**Comment by mjbudd77** [comment]
The QT/SDL version has the git version on its "About fceux" window. I can add this to the GTK SDL version for you. I think I also saw a git hash on the windows version somewhere.

**Comment by Amnesia1000** [comment]
> The QT/SDL version has the git version on its "About fceux" window. I can add this to the GTK SDL version for you. I think I also saw a git hash on the windows version somewhere.

Thank you. I know it is not something that will improve the emulator, but it would be good to have a reference on the subject.

**Comment by mjbudd77** [comment]
This has been added in merge request #153 .
