### ISSUE TITLE
Color mask (?) is darker than other emulator

### ISSUE THREAD

**Issue by Yave-Yu** [TASVideos/fceux#156]
I don't know how to call it, but some game like **Nazo no Kabe - Block Kuzushi** (**Crackout** in EU) uses it.
In FCEUX, it looks darker than other emulator, see screenshots below:
![Nazo no Kabe - Block Kuzushi-0](https://user-images.githubusercontent.com/54294476/89893276-a2f57380-dc0a-11ea-855c-c9b76873aebc.png)
![Nazo no Kabe - Block Kuzushi_000](https://user-images.githubusercontent.com/54294476/89893296-a7219100-dc0a-11ea-861a-76742e8a80fd.png)

**Comment by bbbradsmith** [comment]
What "other" emulator are you referring to, and why do you think FCEUX is doing it wrong?

I know that some emulators do not emulate the colour emphasis controls at all, which could account for you not seeing it in some other emulator... but I don't see the game using this feature (either FDS version, or Crackout). Does the darkness not happen until a later level?

**Comment by bbbradsmith** [comment]
Using password NOBCZ2.CW5103 I can get to level 4-11 where the game does indeed use the blue emphasis bit, which should darken red and green slightly.

I don't see how FCEUX's behaviour is in any way wrong here. This should happen on real hardware as well.

**Comment by Yave-Yu** [comment]
> What "other" emulator are you referring to, and why do you think FCEUX is doing it wrong?

Mesen, BizHawk.

**Comment by bbbradsmith** [comment]
Well, this is not easy to compare. All 3 of these emulators are doing the correct overall behaviour, i.e. the screen should be slightly dimmed and blue tinted at that point.

How much it should be dimmed is a somewhat subjective question. We have some measurements of the resulting signal level at the NESDev Wiki [https://wiki.nesdev.com/w/index.php/NTSC_video#Color_Tint_Bits](NTSC video article) but how that actually displays depends on the contrast curve of the television. You might do a large survey to determine averages, but at some point this is just a matter of opinion as to what curve you prefer.

On top of that, we're all approximating everything as an RGB palette, which can't properly represent the NTSC signal without compromise anyway. Unless we're starting with the same base palette, it's not really fair to compare how one palette is darkened vs. a completely different palette.

So... the long story short is that if you want to argue that FCEUX is too dark, we might need more rationale besides "Mesen is brighter". Currently what FCEUX does is use an implementation of Bisqwit's NTSC signal simulator, and measure the brightness change that produces, then apply that difference to the given base palette colour: [https://github.com/TASVideos/fceux/blob/a2aa55a69cbf4fefa6a35cb579bcf609c9d862c8/src/palette.cpp#L176](palette.cpp line 176)

However, you can also use a custom palette. FCEUX supports 512 entry palettes, not just 64. If you fill in all the entries of a custom palette you can tell FCEUX to use whatever brightness you want for every possible output colour.

**Comment by Yave-Yu** [comment]
Nice, I never know FCEUX support 512 palette.
I tried "all-same" color to 512, and load it in FCEUX, thanks for your advice.
![Nazo no Kabe - Block Kuzushi-0](https://user-images.githubusercontent.com/54294476/89973090-10001c00-dc92-11ea-8753-777735ea7d65.png)

**Comment by mjbudd77** [comment]
This reads like a non-issue. Can it be closed?

**Comment by Yave-Yu** [comment]
> This reads like a non-issue. Can it be closed?

Just a notice this difference, and he told me a solution, so this could be closed.

**Comment by zeromus** [comment]
users with specific demands for emphasis bits should be using 512 color palette. so yeah, closed
