### ISSUE TITLE
SDL backend does not work

### ISSUE THREAD

**Issue by Amnesia1000** [TASVideos/fceux#160]
The GTK version for linux does not work well, the video and audio are locked using SDL as the video backend. OpenGL and Cairo work fine. Qt version works fine too.
Attached video to show well what is happening
[Youtube](https://youtu.be/2XoP_bKhrvA)
Linux Manjaro Gnome (GTK3)

**Comment by mjbudd77** [comment]
Thank you for the video. It was very helpful. However, I did the same test you did on the Manjaro VM that I had previously created before and all worked as expected. 
Compiled with the following commands:
```mkdir buildGTK; cd buildGTK;
cmake -DGTK=1  -DGLVND=0  ..;
make;
```

**Comment by Amnesia1000** [comment]
When I compile with these parameters, "cmake -DGTK=1 -DGLVND=0 .." and "cmake -DGTK=1 -DGLVND=1 ..", the error is only in SDL. Also the error is in OpenGL if the "Enable OpenGL Linear Filter" and "Enable double buffering" options are disabled, when re-enabling them, OpenGL works again.

**Comment by mjbudd77** [comment]
I don't know what to say... I just ran the GTK GUI inside a Manjaro VM and was able to play a game with SDL video, sound, and joystick (gamepad) all fully functional. I changed through every video driver option and all worked without issue. I cannot fix something that I cannot replicate.

**Comment by Amnesia1000** [comment]
It is as you say, it must be a problem with the Nvidia graphics, OpenGL, SDL and GTK, the only thing that does not suit me is that other emulators based on GTK, SDL and OpenGL work well and they are also their own compilations ... The truth is that I have you brought many problems xD I will use the Qt version

**Comment by mjbudd77** [comment]
Before I give up, I will compare my glx code to what is on the snes9x. Maybe I can find something there to try.

**Comment by mjbudd77** [comment]
I looked over the snes9x source code and compared their gtk glx window backend code to mine. I did find some differences that may help. I just pushed out a commit with the updated code. I don't notice a difference on my computer but maybe it will help yours.

**Comment by Amnesia1000** [comment]
Sorry for the delay, since the last update the "trick" of entering the terminal to start the session does not work, to avoid problems I am reinstalling manjaro, just enough to test fceux and know that it is not a problem with the installation, later I will try the new update to know if the problem is fixed

**Comment by Amnesia1000** [comment]
I just compiled the latest version of Fceux, and it remains the same, with DGLVND = 0 and with DGLVND = 1. When I'm in Cairo it works great. With SDL it gets stuck. With OpenGL it gets stuck if "Enable OpenGL Linear Filter" and "Enable double buffering" options are disabled.

**Comment by mjbudd77** [comment]
My most recent changes would have only effected the GLX OpenGL. I would not expect the linear filter to change anything but blur/blend the pixels together when expanding the image. When turning off the double buffering option, I stop calling buffer swaps between the front and back screen buffers. I have added some debug print statements to the GLX context creation code. Can you show me what text that fceux prints out into the terminal when OpenGL now enabled? Also, I want to see what glx visuals are available on your computer. Run this command: 
```
glxinfo >| glxinfo.txt
```
and attach the glxinfo.txt file so that I can view it. Are you still having the desktop crash/logout issue as well?

**Comment by Amnesia1000** [comment]
This is the text in the terminal
GLX visual 0x2b selected
GLX_RGBA: 1 
GLX_USE_GL: 1 
GLX_LEVEL: 0 
GLX_BUFFER_SIZE: 24 
GLX_DOUBLEBUFFER: 1 
GLX_RED_SIZE: 8 
GLX_GREEN_SIZE: 8 
GLX_BLUE_SIZE: 8 
GLX_ALPHA_SIZE: 0 
GLX_DEPTH_SIZE: 0 
GLX_STENCIL_SIZE: 0 
glXIsDirect: 1 

[glxinfo.txt](https://github.com/TASVideos/fceux/files/5079362/glxinfo.txt)

Yes, the login error continues. I do not remember well at this time if the login / logout error was with any backend in the latest versions, but in the latter, putting cairo I could open and close the emulator several times without problems, but when I changed it to OGL, when I wanted to reopen it, the session was closed.
I hope this last information helps something, but it is as you say it must be a problem with the graphics, if the same does not happen on other plates.

**Comment by mjbudd77** [comment]
Unfortunately, I don't see anything wrong with this output and it is almost identical to what I see on my computer. Maybe a clue to see why the X server is logging out. Maybe see if there is anything in the /var/log/Xorg.0.log  or /var/log/Xorg.1.log files that can give some insight on what the X server thinks is wrong. Other than this, I'm out of ideas.

**Comment by mjbudd77** [comment]
Closing issue. Appears to be a low level graphics dependency issue
