### ISSUE TITLE
Fceux does not start if control is connected at startup

### ISSUE THREAD

**Issue by Amnesia1000** [TASVideos/fceux#161]
When trying to open fceux (Qt and GTK alike) the emulator does not start when a bluethoot control is connected.
Turning it off starts without any problem.
This is what the console shows:

./fceux    
Starting FCEUX 2.2.3-interim git...
*** stack smashing detected ***: terminated
zsh: abort (core dumped)  ./fceux

Linux Manjaro Gnome (GTK3)

**Comment by mjbudd77** [comment]
What is the name of the bluetooth game controller you are trying to connect? I have never tried using a bluetooth controller and do not own one. I have been using USB game controllers, which have always worked without issues. Do you have a USB game controller that you can try? If a USB game controller works for you, then I'm willing to bet that there is a bug in the low level SDL code. I will look at the SDL bugzilla to see if there are any open write ups with blue tooth controllers/joysticks.

**Comment by mjbudd77** [comment]
Also, since you are getting a core dump. Maybe try compiling with debug symbols included in the executable and try to get a look at the stack trace. To perform a debug build: 
```
cmake -DGTK=1  -DCMAKE_BUILD_TYPE=Debug  ..;
make -B;
```

**Comment by Amnesia1000** [comment]
I am using the Nintendo Wii U Pro Controller.

Using this parameters, when I open the game with the controller on this time I received this message

./fceux-gtk
Starting FCEUX 2.2.3-interim git ...
Init Joysticks: 1
*** stack smashing detected ***: terminated
zsh: abort (core dumped) ./fceux-gtk

**Comment by Amnesia1000** [comment]
The GTK version is very broken, I can set and assign the controls (bluethoot and USB) but it doesn't take when I press the buttons. I do not know if it is understood, I can assign to button A of the emulator the button A of the control, but when I press it, it does not take it.
In Qt it works perfectly.
