### ISSUE TITLE
Crashing while Launching FCEUX Darwin 2.2.3 on Mac OS Catalina 10.15.6

### ISSUE THREAD

**Issue by meteorwave** [TASVideos/fceux#166]
I don't know if anyone is actively working on the Darwin 2.2.3 build of FCEUX, but when i try to launch the application it immediately crashes.  I saved the crash report below:

Process:               fceux [877]
Path:                  /Applications/fceux.app/Contents/MacOS/fceux
Identifier:            ???
Version:               ??? (???)
Code Type:             X86-64 (Native)
Parent Process:        ??? [1]
Responsible:           fceux [877]
User ID:               501

Date/Time:             2020-08-20 22:49:29.872 -0400
OS Version:            Mac OS X 10.15.6 (19G2021)
Report Version:        12
Anonymous UUID:        206D4BC3-BCA4-3590-076B-719EE2536295

Time Awake Since Boot: 1300 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000
Exception Note:        EXC_CORPSE_NOTIFY

Termination Reason:    DYLD, [0x1] Library missing

Application Specific Information:
dyld: launch, loading dependent libraries

Dyld Error Message:
  Library not loaded: /usr/local/opt/qt/lib/QtOpenGL.framework/Versions/5/QtOpenGL
  Referenced from: /Applications/fceux.app/Contents/MacOS/fceux
  Reason: image not found

Binary Images:
       0x102704000 -        0x102852ff7 + (??? - ???) <F1EE2FA6-173C-3C37-8E01-68911EB1CC89> /Applications/fceux.app/Contents/MacOS/fceux
       0x10dc67000 -        0x10dcf8f47  dyld (750.6) <F9D4DEDC-8296-3E3F-B517-9C8B89A4C094> /usr/lib/dyld

Model: MacBookAir7,2, BootROM 195.0.0.0.0, 2 processors, Dual-Core Intel Core i7, 2.2 GHz, 8 GB, SMC 2.27f2
Graphics: kHW_IntelHDGraphics6000Item, Intel HD Graphics 6000, spdisplays_builtin
Memory Module: BANK 0/DIMM0, 4 GB, DDR3, 1600 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3130
Memory Module: BANK 1/DIMM0, 4 GB, DDR3, 1600 MHz, 0x802C, 0x4D5435324C3531324D3332443250462D3130
AirPort: spairport_wireless_card_type_airport_extreme (0x14E4, 0x117), Broadcom BCM43xx 1.0 (7.77.111.1 AirPortDriverBrcmNIC-1615.1)
Bluetooth: Version 7.0.6f7, 3 services, 18 devices, 1 incoming serial ports
Network Service: Wi-Fi, AirPort, en0
Serial ATA Device: APPLE SSD SM0128G, 121.33 GB
USB Device: USB 3.0 Bus
USB Device: BRCM20702 Hub
USB Device: Bluetooth USB Host Controller
USB Device: Controller
Thunderbolt Bus: MacBook Air, Apple Inc., 27.2

**Comment by mjbudd77** [comment]
From your crash report I see that it failed to load Qt OpenGL shared libraries. The pipeline built dmg file requires 3 packages to be installed via home brew. These are sdl2, qt5, and minizip. You also need zlib to be installed as well although zlib was already part of the base VM that compiled fceux. If you wish to build from source, you can follow what was done in the pipelines/macOS_build.sh file.

**Comment by mjbudd77** [comment]
If you dont have home brew installed you need to get it. Try running these commands to install the necessary dependencies via home brew:
```
brew install sdl2
brew install qt5
brew install minizip
```

**Comment by mjbudd77** [comment]
Following up on this, can you confirm that you have installed the necessary dependencies? Is this still an issue?

**Comment by meteorwave** [comment]
I managed to install homebrew correctly, but unfortunately, I tried your first command line and recieved this error message.  I do not feel comfortable proceeding with my system, until you take a look at this error message:

Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.

If this doesn't end up working would you be able to point me in the right direction to uninstall the homebrew and all the components that came along with it?  I am by no means a programmer, just an amateur.

**Comment by mjbudd77** [comment]
I uninstalled the packages and went through the install process again. I was mistaken, you do not need root permissions to install the pacakges. I updated the commands above (removed the sudo from them).

**Comment by meteorwave** [comment]
okay i was able to sucessfuly install the last two packages, but i could not install the sd12 package:

Error: No available formula with the name "sd12" 
==> Searching for a previously deleted formula (in the last month)...
Error: No previously deleted formula found.
==> Searching for similarly named formulae...
Error: No similarly named formulae found.
==> Searching taps...
==> Searching taps on GitHub...
Error: No formulae found in taps.

**Comment by mjbudd77** [comment]
You read it or typed it wrong.  sdl2  not sd12

**Comment by meteorwave** [comment]
Okay it's working, thanks a bunch!
