### ISSUE TITLE
An ancient bug in Hex Editor which nobody noticed for years and hard to fix

### ISSUE THREAD

**Issue by owomomo** [TASVideos/fceux#171]
There is a bug in Hex Editor, when you add a bookmark to the address outside NES Memory, the next time it launches, the bookmark was moved to NES Memory address.
This is because `storeHexPreferences(FILE*)` doesn't save the edit mode of the bookmark list to the deb file. It seems nobody noticed this bug for a long time.
However there's some problem to solve this bug as the last edit of pref.cpp is very long time ago, maybe it was written in the stone age when Hex Editor only support NES Memory, then it was forgotten in the corner.
I can try to fix it, but now I am facing difficult dilemma choices here:
1. rewrite the logic of `storeHexPreferences(FILE*)`, store the edit mode right after the address or the description. But it would change the storage sequence in the file, make the deb created by the older version of FCEUX incompatible with the newer one. They can't load each other's deb file properly.
2. Store the edit mode index after the bookmark shortcut key preference, this solution is much better compatible with older version because they would stop earlier and don't read the preference file that far, but it's not good for the readability and maintainability of the code.
Which one should I choose?

**Comment by bbbradsmith** [comment]
I think it would be better to keep .deb files backward compatible when possible.
