### ISSUE TITLE
Opening ROM from a lua script (on Linux)

### ISSUE THREAD

**Issue by randomCharacter** [TASVideos/fceux#195]
I was trying to make a lua script that would open specific rom and start emulation. The documentation states that this can be achieved using **emu.loadrom(string filename)** function, but it didn't work. I've tried both asbsolute and relative paths, but neither worked. Eventually I started debugging only to find this piece of code in **lua-engine.cpp**
```
static int emu_loadrom(lua_State *L) {
#ifdef WIN32
	const char* str = lua_tostring(L,1);

	//special case: reload rom
	if(!str) {
		ReloadRom();
		return 0;
	}

	const char *nameo2 = luaL_checkstring(L,1);
	char nameo[2048];
	strncpy(nameo, nameo2, sizeof(nameo));
	if (!ALoad(nameo)) {
		extern void LoadRecentRom(int slot);
		LoadRecentRom(0);
		return 0;
	} else {
		return 1;
	}
#endif
	return 1;
}
```

So my questions are why isn't this documented to only work on Windows, like **table joypad.readimmediate(int player)** and are there plans to add support for this in the future?

**Comment by mjbudd77** [comment]
My apologies. I have not fully combed through the SDL port’s lua engine functionality. It is my goal to make the SDL port function as much as possible like the windows version. I will look into these.

**Comment by randomCharacter** [comment]
I'm glad to hear that. I would be more than happy if I can help somehow. I've tried building project from source, but CMake is failing because of missing package 'minizip'. Install instructions say that I should `follow the instructions in the README-SDL.md file.`, but I'm unable to find that file in the project.

**Comment by mjbudd77** [comment]
Which Linux distribution are you using? You get the development packages for the dependencies through the Linux distributions package manager. For Ubuntu, I believe you use the apt-get utility

**Comment by mjbudd77** [comment]
I would mind if you could throw a few simple test lua scripts my way that I could use to validate my changes with.

**Comment by randomCharacter** [comment]
I've managed to fix this issue. Here is a link where you can see diffs: https://github.com/randomCharacter/fceux/pull/1
If this code is good enough I can send PR to this repository directly.

**Comment by mjbudd77** [comment]
I have merged in your updates. Closing issue.
