### ISSUE TITLE
Testing on Manjaro. 

### ISSUE THREAD

**Issue by svein83** [TASVideos/fceux#196]
I successfully built and installed on Manjaro 20.1.2 today (Kernel 5.8.16-2)

I found a few errors in the build instructions and/or config.

- The README-SDL.md file mentioned in INSTALL doesn't exist.

- The file README contains a list of prerequisites and make/install instructions.

**Install prerequisites:**
`sudo pacman -Syyu sdl2 cmake qt5-base minizip zlib lib32-zlib mesa glu lib32-mesa lib32-glu gcc gcc-libs lib32-gcc-libs`

**Clone the repo:**
`git clone https://github.com/TASVideos/fceux.git`

**Compile and Install**
`cd fceux`
`cmake -DCMAKE_BUILD_TYPE=Release`
`make`

_Or to use 4 CPU cores plus HT:_
`make -j 8`

**Install:**
`sudo make install`

**A few minor errors**
The installed fceux.desktop file had wrong paths for both the executable file and the icon.

I hardlinked fceux and copied the icon to fix it:

`sudo cp -l /usr/local/bin/fceux /usr/bin/fceux`
`sudo cp fceux.png /usr/share/pixmaps/fceux.png`

**Open File Dialog**
The configured filter hides all directories. Select "All files" as a workaround to enable browsing for ROMs.

**Comment by mjbudd77** [comment]
I believe if I change the build and install directions specify the proper install path, then you would not have the desktop icon pathing issues. Do you agree with me changing it to this?
```cmake  -DCMAKE_BUILD_TYPE=Release  -DCMAKE_INSTALL_PREFIX=/usr  ```
By doing this, the installation path will be /usr instead of the cmake default of /usr/local.

**Comment by svein83** [comment]
Yeah.

It will probably work. I'll do a reinstall and see.


Could the filter string for the "Open File Dialog" be corrected so it won't hide regular directories?

**Comment by mjbudd77** [comment]
Yes, I will look at the open file dialog now.

**Comment by mjbudd77** [comment]
Are you referring to the Open ROM file dialog? I'm not having this issue. I can see all directories.

**Comment by svein83** [comment]
> Are you referring to the Open ROM file dialog? I'm not having this issue. I can see all directories.

Yes. Nothing except .nes files and two or three folders are displayed so browsing is impossible. If I change it to "All Files (*)" then everything is visible.

**Comment by mjbudd77** [comment]
I also forgot to mention that there are two file dialog options in the Qt gui. By default, the gui is coded to use the built in Qt file browser, but you can also tell the gui to use the native os desktop file browser instead. Which for manjaro is probably the gnome GTK based file browser. You can change this option in the gui config window as accessed via the main menu -> options -> gui config

**Comment by svein83** [comment]
The file browser GUI options don't seem to change anything. I'll try a clean rebuild and reinstall and report my findings.

**Comment by mjbudd77** [comment]
On line 720 in ConsoleWindow.cpp, will you try adding an QDir::AllDirs into the argument bitwise OR expression. If it works i will add it to all apoocurances in the gui

**Comment by mjbudd77** [comment]
After more reading, I think that has to be the issue. I went through all of the file browser instances in the Qt GUI and added this argument to each one. I have a pull request that I will be merging into the main repo as soon as the pipeline passes.

**Comment by svein83** [comment]
Cool

About the fceux.desktop file.
Perhaps generating it with correct path entries during install is better?

**Comment by mjbudd77** [comment]
I gave some thought about the install path. Every linux distro that previously packaged fceux used /usr as the install prefix. I don't really see a reason to change it, but a simple script probably wouldn't be too hard to make either. I will try something out.
Can you confirm that my most recent change has fixed your file browser directory visibility issue?

**Comment by negativeExponent** [comment]
since directories and visible files are mentioned, can we add standard UNIF extension as well? that should be .unf and .unif

**Comment by mjbudd77** [comment]
I just pushed out a commit that adds all usable non-compressed files to the filter list for the Qt GUI. This includes NES, NSF, FDS, and UNF (UNIF). I noticed that the SDL port is not handling zip files correctly and am looking into it.

**Comment by negativeExponent** [comment]
thanks for the fast response. now for this topic, dunno how "makefiles" are suppose work when use as for example "make install/uninstall", but the fceux.desktop links has to be updated based on prefix flags used on cmake. Fcuex by default uses /usr/local but the .desktop uses /usr/bin. I have since been symlinking to remedy the issue.

**Comment by mjbudd77** [comment]
I edited the installation README to say that the cmake installation path should really always be set to /usr instead of the cmake default /usr/local. Look for this in the README file:
```
cmake  -DCMAKE_INSTALL_PREFIX=/usr
```
The -DCMAKE_INSTALL_PREFIX=/usr argument to the cmake command will ensure that the installation is always based at /usr instead of /usr/local. All the various linux distros are packaging fceux to be installed in /usr and I don't see a reason to change it.

**Comment by mjbudd77** [comment]
If we just make the assumption that all linux installations should be installed to /usr, then I believe that everything in this issue has been addressed. Does everyone agree?

**Comment by svein83** [comment]
> I gave some thought about the install path. Every linux distro that previously packaged fceux used /usr as the install prefix. I don't really see a reason to change it, but a simple script probably wouldn't be too hard to make either. I will try something out.
> Can you confirm that my most recent change has fixed your file browser directory visibility issue?

Sorry about the slow reply. I just did a fresh build and install.
I confirm that the file browser works like expected now.

I agree we can close the issue.

**Comment by mjbudd77** [comment]
Closing issue.
