### ISSUE TITLE
scons build failure

### ISSUE THREAD

**Issue by unassumingbadger** [TASVideos/fceux#197]
git clone https://github.com/TASVideos/fceux.git
cd fceux
scons

arm-linux-gnueabihf/glib-2.0/include src/fceu.cpp
In file included from src/drivers/sdl/dface.h:4,
                 from src/drivers/sdl/sdl.h:11,
                 from src/fceu.cpp:81:
src/drivers/sdl/input.h:6:10: fatal error: common/configSys.h: No such file or directory
 #include "common/configSys.h"
          ^~~~~~~~~~~~~~~~~~~~
compilation terminated.
scons: *** [src/fceu.o] Error 1
scons: building terminated because of errors.

Okay lets copy (not move) src/drivers/common directory into src/drivers/sdl/

scons
.
.
.
src/drivers/common/os_utils.cpp:12:10: fatal error: common/os_utils.h: No such file or directory
 #include "common/os_utils.h"
          ^~~~~~~~~~~~~~~~~~~
compilation terminated.
scons: *** [src/drivers/common/os_utils.o] Error 1
scons: building terminated because of errors.

edit  #include "common/os_utils.h" to  #include "os_utils.h"

scons
.
.
.

In file included from src/drivers/sdl/input.cpp:29:
src/drivers/sdl/sdl-joystick.h:8:10: fatal error: sdl/main.h: No such file or directory
 #include "sdl/main.h"
          ^~~~~~~~~~~~
compilation terminated.
scons: *** [src/drivers/sdl/input.o] Error 1
scons: building terminated because of errors.

You've shuffled things around and never corrected their locations. 
I could go on, but I wont.

**Comment by svein83** [comment]
See the README file under 2 - Installation

`git clone https://github.com/TASVideos/fceux.git`
`cd fceux`
`less README`

---

<pre>
...
...
2 - Installation
----------------
The old scons build system is no longer supported.
Fceux can be compiled and built using the cmake build system......
...
...
</pre>

**Comment by unassumingbadger** [comment]
I was so used to doing it the old way. Sorry and thanks.

**Comment by svein83** [comment]
NP
