### ISSUE TITLE
Question: Fixed zoom level?

### ISSUE THREAD

**Issue by shentino** [TASVideos/fceux#205]
Is there a way to have the zoom level fixed instead of auto-adjusting based on window size?

I'd prefer to for example keep an integer zoom level.

Version: master as of October 26, 2020, linux port (apparently both Qt and GTK3)

**Comment by shentino** [comment]
I remember an old option that could independently select X and Y zoom, under the video config menu

**Comment by mjbudd77** [comment]
I did not really think that those options would be needed anymore since you can just drag the corner of the screen to the desired size. And I always thought it was silly to have separate x and y scales because having them at different values would make the image look stretched. I can put these controls back into the gui video config if that is preferred.

**Comment by shentino** [comment]
It would be preferred to at least be able to specify the size numerically.  You'd be surprised how hard it is to get a pixel perfect integer zoom otherwise :)

**Comment by shentino** [comment]
To be clear I wasn't really suggesting the separate ones, just citing that as what did before.

So yeah, ideally a "scale to fit" checkbox alternating with a number spinner that could specify the zoom option directly and numerically.

Trying to stretch-zoom by adjusting the window size is very imprecise and tbh it looks worse at a non integer zoom level from that than it does stretching with a non-square aspect ratio :D

**Comment by shentino** [comment]
> I did not really think that those options would be needed anymore since you can just drag the corner of the screen to the desired size. And I always thought it was silly to have separate x and y scales because having them at different values would make the image look stretched. I can put these controls back into the gui video config if that is preferred.

And to be clear I agree that a non 1:1 aspect ratio is indeed quite silly :).  I'd remove that tbh.

**Comment by mjbudd77** [comment]
Just merged a change that should give you the control you want on the Qt Video Config GUI. If you are happy with it, please close this issue and the other one (#99)

**Comment by shentino** [comment]
Actually it seems to be a bit broken, should we get together for a beta testing pow-wow?

**Comment by mjbudd77** [comment]
Message me on the IRC?

**Comment by shentino** [comment]
Will do, was kinda busy irl so sorry for being late

**Comment by shentino** [comment]
Closed as resolved

**Comment by shentino** [comment]
This works.
