### ISSUE TITLE
"Scroll Lock" key for Family Keyboard support is difficult to use on some laptops

### ISSUE THREAD

**Issue by barbeque** [TASVideos/fceux#214]
Both my Macbooks and my Thinkpad X230 lack a "Scroll Lock" key that can be used to switch the Famicom's Family Keyboard input mode on.

It looks like the check for the "Scroll Lock" key is hardcoded in [`src/drivers/sdl/input.cpp`](https://github.com/TASVideos/fceux/blob/master/src/drivers/sdl/input.cpp#L456), `src/drivers/Qt/input.cpp`, and `src/attic/pc/input.c` as far as I can tell. There seems to be no handling for this feature in `win/input.cpp` although I think the related flag there is meant to be `cidisabled`.

I would like to make it so you can at least reconfigure the SDL and Qt versions to a key I do have, like F11.

I'm not entirely sure what the best way to go about changing this would be. I thought about adding it to the "hotkeys" set but neither `KeyboardCommands` in the SDL driver nor the Qt driver seem to use the config at all. Is the hotkeys implementation not meant to go any 'deeper' than the GUI or would this be a good idea to start with?

Thanks for taking the time to read this issue!

**Comment by mjbudd77** [comment]
I will add a hot key to the Qt GUI to toggle this function for you.

**Comment by mjbudd77** [comment]
The merge mentioned above has made the family keyboard enable toggle function a configurable hot key for the Qt GUI. Please verify that this fixes your issue.

**Comment by barbeque** [comment]
Seems to work great, although I have trouble pushing F1 in Family BASIC (possibly because of the Fn-key combination) every other key seems to work. I will look into that.

I also noticed that the default hotkey bindings looks a little weird on my self-built install vs. the one that I got from Homebrew:

Just built:
![Screen Shot 2020-11-01 at 11 36 08 AM](https://user-images.githubusercontent.com/423811/97811258-8d567f80-1c36-11eb-82e6-1c28af0818c9.png)

Homebrew:
![Screen Shot 2020-11-01 at 11 37 25 AM](https://user-images.githubusercontent.com/423811/97811269-9fd0b900-1c36-11eb-9df8-e5c7b98f22f2.png)

I'll try to rebind these to F1..etc later and see if it works properly then. Thanks for the super-fast turnaround!

**Comment by mjbudd77** [comment]
The one from home brew, if you did a 
```brew install fceux```
That is loading a very old version of fceux that uses gtk instead of Qt and also uses a much older version of SDL. I'm not sure that the key mappings between SDL1.x and SDL2 are the same. I would not use the the home brew for testing new features. The dmg package from the autobuilds would be a better choice. To be safe, I would remove the old fceux config and let the new executable generate the config clean. 
```
rm ~/.fceux/fceux.cfg
```

**Comment by barbeque** [comment]
That fixed it, thank you! 👍

**Comment by mjbudd77** [comment]
Can this be closed now?

**Comment by barbeque** [comment]
Yes, thanks!

The key repeat inside Family BASIC is acting a little funny for modifiers (sometimes the shift key sticks even after it’s been released, and only right shift seems to work) but I can’t make a clean reproduction case yet. I’ll open a new issue for that if I can figure out what the problem is. 

Thanks again!!
