### ISSUE TITLE
Lua scripting: relative path loading seems broken

### ISSUE THREAD

**Issue by brianlheim** [TASVideos/fceux#215]
According to the lua scripting manual:

> `emu.loadrom(string filename)`
>
> Loads the ROM from the directory relative to the lua script or from the absolute path. Hence, the filename parameter can be absolute or relative path.
> If the ROM can't be loaded, loads the most recent one.

and

> `bool movie.load(...)`
> 
> Loads and plays a movie from the directory relative to the Lua script or from the absolute path. [...]

however, this doesn't seem to be true on macOS. here's the steps i followed.

1. launch fceux.app
2. load this script:

```lua
emu.loadrom("/absolute/path/to/SMB.nes")
result = movie.load("/absolute/path/to/foo.fm2", true)
print(result)

```

3. run the script. since the fm2 and nes files exist at those absolute paths, this works fine for me, and prints "true"
4. close and relaunch fceux.app.
5. load this script:

```lua
emu.loadrom("roms/SMB.nes")
result = movie.load("fm2s/foo.fm2", true)
print(result)
```

my directory structure is:

```
[brianheim@BrianMBP tmp]$ tree
.
├── fm2s
│   └── foo.fm2
├── load_and_run.lua
└── roms
    ├── SMB.cdl
    ├── SMB.nes
    └── SMB.nes.ram.nl

2 directories, 5 files
```

6. run the script. i get an error dialogue saying `Error opening "../roms/SMB.nes"!`. this doesn't seem to make sense since that isn't the path i passed in, but during an earlier session in fceux i did call `emu.loadrom("../roms/SMB.nes")` successfully, before rearranging my files, so perhaps this is leftover from that somehow. the fm2 movie seems to load fine, i see "true".
7. close and relaunch fceux.app.
8. load the SMB ROM manually using the menu.
9. load this script:

```lua
result = movie.load("fm2s/foo.fm2", true)
print(result)
```

with the same directory layout as before.

10. run the script. i see "false".

---

i see 3 distinct things that are unexpected:
1. i can't call `emu.loadrom` or `movie.play` with a relative path, relative to the lua script
2. `movie.load` with the same filename appears to succeed if a ROM isn't loaded, when it would fail if a ROM were loaded
3. the error dialogue when failing to load a ROM contains the wrong, or at least a misleading path

this is with a freshly installed fceux.app downloaded from the website, revision ed61b970. i've previously run fceux on my system; are there config directories or other state i should clear to make sure this is reproducible?

**Comment by mjbudd77** [comment]
This issue should now be resolved in the update mentioned above. Please verify for me.

**Comment by brianlheim** [comment]
@mjbudd77 thanks! this seems to be fixed now.
