### ISSUE TITLE
Hex editor causes non-deterministic movie playback

### ISSUE THREAD

**Issue by brianlheim** [TASVideos/fceux#217]
macOS 10.15 Catalina, official fceux build from revision ed61b97

steps to reproduce:
1. open fceux
2. open hex editor
3. open a rom (i used SMB)
4. play an fm2 movie (i used happylee's WR TAS - http://tasvideos.org/1715M.html)

on my system, movie playback will randomly and unpredictably differ from the deterministic playback i see without the hex editor open. it usually starts to happen within the first minute or so of playback (in level 1-1 or 1-2). sometimes movement will stop, sometimes it looks like button presses are dropped, and sometimes new button presses happen (e.g. the game will suddenly pause itself).

similarly, if i open the hex editor while a movie is playing, the playback will become non-deterministic within about a minute.

**Comment by mjbudd77** [comment]
I was able to reproduce this but don’t fully understand why this is happening. This one may take a while to sort out.

**Comment by mjbudd77** [comment]
Wow, this one was hard to find, but I think I fixed it. Please confirm

**Comment by brianlheim** [comment]
thanks
