### ISSUE TITLE
Qt/Lua: Lua console only prints 255 characters at a time

### ISSUE THREAD

**Issue by brianlheim** [TASVideos/fceux#219]
the luaConsoleOutputLine struct always copies up to 255 characters from the input string, but this behavior is never checked for truncation. this has the effect of truncating anything posted in the lua window to 255 characters, including error backtraces.

https://github.com/TASVideos/fceux/blob/master/src/drivers/Qt/LuaControl.cpp#L30-L49

i would fix this myself but i don't know what would be best in your opinion @mjbudd77 . it looks like this class is designed to  hold 60 "lines" at once, but never checks that the input strings are not multi-line themselves. to me a reasonable solution would be to treat the entire buffer space as a single ring buffer of fixed length, rather than 60 small buffers.

**Comment by brianlheim** [comment]
can reproduce with this lua script:

```lua
a = ""
for i = 0,255,1
do
    a = a .. i
end
print(a)
```

**Comment by mjbudd77** [comment]
The circular buffer is in place to safely pass the string data from the emulation thread to the main GUI thread. If the emulation thread calls Qt GUI functions it will cause a crash. My initial thought is to just change the char text[256] to be a std::string text so that we will not be length limited. I will try it out.

**Comment by mjbudd77** [comment]
Actually not sure if std strings are thread safe. I will change the buffer to be more like your idea.

**Comment by mjbudd77** [comment]
I changed the ring buffer to be one continuous 4k block. I used your example script as a test and it seemed to handle the output correctly.  I believe this issue is now resolved. Please confirm that you agree.

**Comment by brianlheim** [comment]
@mjbudd77 thanks! it appears to be fixed. however, i do want to note that while i was looking into this, i noticed certain places in the project code have the potential for buffer overruns, for example in both callsites of CallLuaTraceback: https://github.com/TASVideos/fceux/blob/master/src/lua-engine.cpp#L2036-L2037, https://github.com/TASVideos/fceux/blob/master/src/lua-engine.cpp#L6157-L6158. you may want to pay attention to these too.
