### ISSUE TITLE
mapper 198  When prom is less than 0x28, the last bank error

### ISSUE THREAD

**Issue by kwjxqy** [TASVideos/fceux#24]
https://github.com/TASVideos/fceux/blob/a6219f50069c3632c2ae24bfdf43fb3d4e527ad7/src/boards/mmc3.cpp#L1118
https://github.com/TASVideos/fceux/blob/a6219f50069c3632c2ae24bfdf43fb3d4e527ad7/src/boards/mmc3.cpp#L1119

**Comment by g0me3** [comment]
there is no proms less than that, this mapper is only for one rom "Tenchi wo Kurau II - Shokatsu Koumei Den (J) (PRG0) [T+Chi]" if you see any other roms with this mapper, it assigned incorrect. instead just use regular mmc3 mapper with battery backed ram and no CHR ROM.
