### ISSUE TITLE
mapper 256 and 413 support

### ISSUE THREAD

**Issue by hossbags2** [TASVideos/fceux#264]
any chance of adding support for those mappers

**Comment by ClusterM** [comment]
Actually mapper 256 supported as UNIF mapper OneBus. Need to add numeric support too. 413 is more difficult to add, i can't find any description about it.

**Comment by ClusterM** [comment]
upd: as i can see mapper 256 already supported by latest builds.

**Comment by hossbags2** [comment]
when I try load a game using mapper 256, I get error CHR-RAM size < 1k is not supported

**Comment by ClusterM** [comment]
OneBus is the only mapper without CHR-ROM (all CHR data stored in PRG region) __and__ without CHR-RAM. So maybe we should remove this check?

**Comment by ClusterM** [comment]
I added support for zero-sized CHR for NES 2.0 ROMs.
