### ISSUE TITLE
Graphical and tools features

### ISSUE THREAD

**Issue by Chipsum** [TASVideos/fceux#273]
Hi
One of the main reasons that I use Mesen emulator over Fceux is the debugging interfaces.
PPU viewer and Nametable viewer specifically , it needs a grid with mouse cursor aligned to tile (like a magnet :3).
it's very hard to get PPU address from the NameTable compared to Mesen. 
Also copying images from PPU/Nametable viewer to clipboard and palette export.
Options to get PPU viewer display tiles with current palette used.
A sprites viewer too, with coordinates info and mirroring, priority ...etc
I wish it's implemented.

**Comment by bbbradsmith** [comment]
Not quite the same as a dedicated sprites viewer but luaScripts/Sprites.lua has a really nice script where you can hover over a sprite and get a display of its data.

**Comment by Chipsum** [comment]
@bbbradsmith 
I really like the sprites lua script (I tried a lot of lua scripts I must have missed that one)
The major change that I really wish to see is an optimized version of NameTable
![image](https://user-images.githubusercontent.com/37517008/102920788-9ec84500-448b-11eb-87b9-3453cf6910f8.png)

- Mouse cursor magnet-like movement over the NameTable to ease getting info about a tile.
- Change the information section in bottom to the right like Mesen , it's more relaxing and also prevents getting hidden since 
   Fceux's Nametable window is kinda taller.
- An 8x8 grid , and 16x16 attributes one too if possible.
- Ability to highlight a tile from PPU Viewer, on NameTable.

Especially the grid, I kinda feel lost without it on Fceux.

**Comment by bbbradsmith** [comment]
I agree that a grid option would be quite helpful in the nametable viewer.

**Comment by mjbudd77** [comment]
I wouldn't mind helping out with this on the Qt/SDL port. I have been trying to get Mesen to build on Linux CentOS8 but fails due to some missing Google-Drive dependency (which is very annoying). Since CentOS8 is about to become a beta test environment for Red Hat, I'm considering moving to Ubuntu. If I can get Mesen to build and run there, then I can do a more detailed comparison and see what functionality could be brought over.

**Comment by Chipsum** [comment]
@mjbudd77 
You can, I actually tested it on Mint it works fine.

**Comment by mjbudd77** [comment]
I was able to get Mesen to run In Ubuntu. I have started looking into how it works and comparing to fceux. However, I will not be making any major changes to fceux until after the 2.3.0 release is official.

**Comment by Chipsum** [comment]
Dunno but even on linux, the window is kinda taller and can't resize it (other window also can't resize, like debugger).
it's compared side by side to Mesen's nametable.
![image](https://user-images.githubusercontent.com/37517008/103421646-c57a3000-4b9d-11eb-862c-6422d4f72bd8.png)

**Comment by mjbudd77** [comment]
I just pushed an update to the PPU pattern and name table viewers for the Qt (Linux/MacOS) versions. Its as functional as it used to be (but still not completely done). However, I would like some feedback to know if I'm on the right track here. You will see the nametable viewer window layout looks more like mesen now.

**Comment by Chipsum** [comment]
@mjbudd77 

That's extremely and exactly better now.

Since it's still not completely done I will not talk about the behavior of some features, but at least I will mention it :

- Nametable is not updating till I click on the main fceux window then get back to Nametable.
- Initial Nametable window starts with max zoom meanwhile it's x1 in the menu.
- Nametable windows doesn't fit accordingly with zoom.
- Selecting a tile is buggy in terms of the white square selected tile.

But Since it's not complete yet, this is a big change I never though I will see this in Fceux I really enjoy this.
I liked the custom grid color a lot, tile editing in PPU Viewer and palette choosing , enabling/disabling grid,
Well done honestly

![image](https://user-images.githubusercontent.com/37517008/106278594-4418ca80-623b-11eb-95a8-cf9a559b50f7.png)

**Comment by mjbudd77** [comment]
Thank you for the feedback. I’m glad to see that you like it. I should also mention that I coded some hot keys for the name table viewer that are active with the viewport has input focus. You can move the tile select box around with the arrow keys and zoom in/out with the minus/plus keys. Currently I only have it where you have to left click the mouse to select a tile, but I plan to make the tile select focus policy be configurable between  click and hover via the menu. Some things I plan to add are: a context menu for the viewport and selected tile view inside tile info framed area. I will also look more into the items you mentioned.

**Comment by mjbudd77** [comment]
I believe I have fixed the items you mentioned. I have added a few more features but I think I'm mostly done. I've changed a lot of code here and could use some help testing. Does everything seem to be working?

**Comment by mjbudd77** [comment]
@Chipsum , I believe the name table viewer update is now complete. Please review

**Comment by Chipsum** [comment]
@mjbudd77 Thank you for the update, I will review it next week I am really busy at work.

**Comment by Chipsum** [comment]
@mjbudd77 
It's really working neat, I loved it.
Especially the Focus Policy (Hover), it's smooth and fast performance overall about the Nametable and PPU viewer.
For now for me this is nearly perfect, but It still lacks some features (But I think you are aware of them), like the sprites viewer and palettes viewer with export to ACT format option ...etc
Maybe if you assemble them (NameTable, PPU Viewer, Sprites Viewer ..etc) in one window is better, or maybe the ability to choose to pull one of them out to a separate window, but that's just my opinion based on how comphy I feel when I use those tools.

I will wait for the windows version too but with this awesome update I can't complain, nothing but a dream came true for me, I really appreciate that. :clap:

**Comment by mjbudd77** [comment]
@Chipsum 
Good to hear that it is functioning as expected. I plan to add the missing sprite viewer and palette view later this year. You can also currently view the palette on the ppu viewer window, but it not arranged as nicely as mesen’s layout. I will not be back porting this change to the Win32 version, however, the Qt/SDL version now will also run natively in windows. It is the qfceux64.zip download.

**Comment by mjbudd77** [comment]
![Uploading 71539B62-096D-483C-8DAF-B14CA2A1E3EC.jpeg…]()

**Comment by mjbudd77** [comment]
Implemented my first cut at the Sprite viewer.

**Comment by Chipsum** [comment]
Neat
If you can make the X,Y positions of the sprite in Hex, I did not like it in decimals in Mesen back then.

**Comment by mjbudd77** [comment]
I will add an option for that

**Comment by vadosnaprimer** [comment]
Something's wrong with the "embedded" image.

**Comment by Chipsum** [comment]
@mjbudd77 
> Qt/SDL version now will also run natively in windows. It is the qfceux64.zip download.

Yeah in fact I tested the windows version since I was working on it.
![image](https://user-images.githubusercontent.com/37517008/115094397-45da5c00-9f15-11eb-9318-c6a4d4329789.png)

**Comment by mjbudd77** [comment]
![zelda1SpriteView](https://user-images.githubusercontent.com/44712797/115095924-1ade1100-9ef1-11eb-9e33-7e6bcfd38b2f.png)
I added a checkbox to allow for the sprite position to be display in either decimal or hex.

**Comment by mjbudd77** [comment]
Sprite preview area has now also been added. Must be opened via view menu.

**Comment by Chipsum** [comment]
I think the tile view area is bigger, I suggest this model
![image](https://user-images.githubusercontent.com/37517008/115124943-12eba300-9fbd-11eb-8c0e-3f04f448a923.png)

But the preview sliding to the right is not a bad idea too.

**Comment by mjbudd77** [comment]
I like the compactness of your layout suggestion. Only downside is that the preview mode wouldn’t be able to be shown x2 size. Not sure if that matters or not. How much detail needs to be seen in the tile view and preview areas in order to be useful? Did you make this modification to your own fork of the project?

**Comment by Chipsum** [comment]
Humm, the x2 size of the preview is not that important , I always used Mesen's sprite viewer to see what's going on with sprites and their properties (position , bg priority).
Maybe if it's possible I would suggest the zoom in model with scroll bars.
Another thing I would suggest is the copy to clipboard feature (just like mesen) , it's useful for sprites rippers / maps in nametable ..etc.

**Comment by Chipsum** [comment]
Nice
![image](https://user-images.githubusercontent.com/37517008/116001396-26fe5880-a5ec-11eb-97c0-6575c0573826.png)

I suggest hover as the default focus policy (Since users that likes to click so much they should select the click policy manually :3 )

**Comment by Chipsum** [comment]
Hex Viewer need font increase feature to be honest (font select too maybe)
![image](https://user-images.githubusercontent.com/37517008/116001579-fa970c00-a5ec-11eb-9302-246206f847dd.png)
I also like to see alternative columns coloring to differentiate between bytes.

**Comment by mjbudd77** [comment]
> I suggest hover as the default focus policy (Since users that likes to click so much they should select the click policy manually :3 )
I will make the focus policy a saved configuration parameter so that it saves your preference.

**Comment by mjbudd77** [comment]
> Hex Viewer need font increase feature to be honest (font select too maybe)
> I also like to see alternative columns coloring to differentiate between bytes.

I just added a font selector to the hex editor and added two new coloring options (accessible via view menu)
First coloring option is to highlight the cursor selected row and column.
Second coloring option is to have alternate column coloring.
Let me know what you think.

**Comment by Chipsum** [comment]
@mjbudd77 

That's awesome , exactly what Fceux deserved for a Hex Viewer (Now I kinda feel like I am on 010 Editor, one of the best Hex Editors out there).

![image](https://user-images.githubusercontent.com/37517008/117028592-c4950e80-acf5-11eb-884c-4e6daa246550.png)

:heart:

**Comment by Chipsum** [comment]
@mjbudd77 
Oh about that, it's just like how other emulators export the palette to act format (Photoshop's Color Table)
Since a lot of modders like to have a ready palette (even that for NES 4 colors is not that bothersome)
why act rather than pal , I think from my experience it's the most supported palette format since it's file structure simple too.
it consists of rgb of a color in hex followed by the second color and so on.
The feature is helpful with 256 colors palettes (like GBA), after all I think we don't need this feature for Fceux anyway
but if you manage somehow to add it , it will save modders some time to get the correct palette ready to use for the bindary CHR-ROM graphics if you know what I mean.

**Comment by mjbudd77** [comment]
After comparing the pal and ACT file formats, they look very similar. But the NES color palette is only 64 colors, how do I get 256 colors out of this to fill out the full ACT file?

**Comment by Chipsum** [comment]
@mjbudd77 
It's not obligatory to fill in all 256 colors in act format, even so you can fill the empty ones with black for example.
But it's not necessary, I experienced that a lot with act files, most of the cases I created 16 colors only palette (when I dealt with snes and megadrive).

**Comment by mjbudd77** [comment]
I added an export in ACT format option in the palette editor window that will output the full nes palette to an ACT file. Is this what you are looking for?

**Comment by Chipsum** [comment]
@mjbudd77 
Oh no, I did not mean the default NES palette.
I mean the current's game's palette:
![image](https://user-images.githubusercontent.com/37517008/118375805-0490a700-b5bc-11eb-905b-04596d122b2b.png)

**Comment by Chipsum** [comment]
You can add it to the context menu
![image](https://user-images.githubusercontent.com/37517008/118376001-4bcb6780-b5bd-11eb-80fb-56bf915f1ae0.png)

Exporting the two rows of 16 colors once.

**Comment by mjbudd77** [comment]
I added the functionality you are looking for like suggested, let me know if it is correct. I do not have adobe photoshop and cannot fully test.

**Comment by Chipsum** [comment]
@mjbudd77 
Amazing, Yep it's working as expected :heart: 
Yep Gimp can load it, aseprite, and almost most tools out there, ACT format is a famous one among palettes formats especially in the modding and emulation community.Thanks a lot.
![image](https://user-images.githubusercontent.com/37517008/118418607-f3759200-b6b0-11eb-876a-5508cc03d4b4.png)

**Comment by mjbudd77** [comment]
So a lot has been done with this issue. Is there anything left to do? It’s getting hard to track what still needs to be done when the issue chain is getting so big

**Comment by Chipsum** [comment]
@mjbudd77 
I strongly agree that a pause is needed for this issue.
I will make it closed for now, and I will continue in the future in later separate issues.
Well done honestly and thank you for making this changes a dream come true :+1: :heart: :tada:
