### ISSUE TITLE
Is CHR-RAM <1k safe now?

### ISSUE THREAD

**Issue by bbbradsmith** [TASVideos/fceux#277]
A question about an edit by @ClusterM 

This edit to supposedly remove "unreachable" code: ed4d1a721753cfdfc4688c1c94dc22fe0b58fe67

Undoes a check for CHR RAM size <1k added with this commit: e8597862f1f35b8c5d4f8570f256750395a7716b

It's been months so my memory on this is not fresh but as I recall a CHR-RAM of less than 1k in the header produced a memory corruption vulnerability, which is why that rejection test was added. Has this been addressed? I don't see anything in the comment history.

**Comment by bbbradsmith** [comment]
Found the original issue that caused me to address that in the first place:

https://github.com/TASVideos/fceux/issues/109

**Comment by g0me3** [comment]
try if this https://github.com/TASVideos/fceux/commit/395af9d283baaf7eec808918a4d6b1c2299cae6e (and two subsequent) solved the problem for inex2.0 at least

**Comment by bbbradsmith** [comment]
That was the commit just before the code was removed though?

The problem, if I recall correctly, is that if the allocated CHR size is less than 1024, the VROM allocation is shorter than what gets provided to the emulation in 1k packets, so... you have a <1k allocated buffer that the emulated program (the 6502 code in the NES ROM) is allowed to read and write 1k worth of. Some of that 1k is out of bounds. Knowing this, a malicious ROM might be created.

I don't think this problem affects CHR RAM size of 0, only of size < 1024, just an iNES 2 header with abnormally small CHR-RAM size.

**Comment by bbbradsmith** [comment]
Created a pull request to address this differently. If you don't want CHR RAM < 1k to be an error condition, fine, but please prevent giving the NES ROM access to an open memory hole.
