### ISSUE TITLE
FCEUX doesn't open

### ISSUE THREAD

**Issue by LordOfBricks** [TASVideos/fceux#28]
So i installed FCEUX normally, there were no errors.
the commands i used:
`scons
scons install`
Since the rest is just optionall.
Now if i go and search for FCEUX i find a programm but when i try to open it nothing works.
Im on Linux Mint 19.1

**Comment by zeromus** [comment]
are you sure it doesnt require issuing a rom path on the commandline?

**Comment by zeromus** [comment]
If you can't issue a rom path on the commandline, then you don't need to be using linux.
