### ISSUE TITLE
Issues with adding in RunAhead support

### ISSUE THREAD

**Issue by Dwedit** [TASVideos/fceux#282]
Helo, I'm trying to add in RunAhead support to the emulator.  But in order to get this feature working, the stability of savestates needs to be improved greatly.

What is RunAhead?  It's a feature that improves input latency by showing the player a future frame (X frames ahead) instead of the current frame.  A NES game will usually have at least one frame of internal lag, due to the screen displaying the result of the previous frame's game logic.  This frame of internal lag will have no response to your inputs, so it can be 'deleted' to reduce total input latency by a whole frame.

RunAhead's basic algorithm:  (To show a future frame X frames later)

* Run 1 frame (Do not output sound or video)
* Save State
* Run X - 1 Frames (Do not output sound or video)
* Run 1 frame (Output sound and video)
* Load State

Some games are working fine with RunAhead right now, such as Super Mario Bros. 

But Castlevania 3 JP is doing this:
![corrupt nametables](https://i.imgur.com/6swKFBT.png)

This problem is not exclusive to RunAhead, you can see it on normal FCEUX by repeating this sequence: Save State, Advance Frame, Load State, Advance Frame...

So the problem right now is overall stability problems after loading savestates.

**Comment by g0me3** [comment]
tried to do the same save state, advance, load state, advance. all looks fine for me.

**Comment by Dwedit** [comment]
Has to be done from power-on.

**Comment by Dwedit** [comment]
Well I have a plan of action for how to debug this... It looks like fceumm-libretro has the exact same problem, so I'll try to diagnose it and fix it there, then port the fix over to FCEUX.

**Comment by g0me3** [comment]
try if this will work

**Comment by Dwedit** [comment]
Confirming by tracelog that at Frame 7 of Akumajou Densetsu, the wrong bank is mapped into B6B9 if you do the Save / Load / Save / Load thing every frame.

**Comment by Dwedit** [comment]
Confirming this sequence of actions causes an issue:

Load ROM Akumajou Densetsu
Pause, Power Button
Advance Frame 5 times
Save State
Advance Frame
Load State
You get the wrong bank loaded into 8000-BFFF.
