### ISSUE TITLE
Invalid array size when parsing .nl files?

### ISSUE THREAD

**Issue by ClusterM** [TASVideos/fceux#283]
I just noticed that my .nl file:

    $0002/02#COPY_DEST_ADDR#
    $0004/02#TMP#

drives fceux to show overlapped arrays:
![image](https://user-images.githubusercontent.com/4236181/103212663-812c2d00-491c-11eb-9ce8-8f44a1c12b3b.png)

After some investigation i found that fceux always adds 1 to array sizes.
debuggersp.cpp:

		if (size && cur->name) // Array definition line
		{
			int arrlen, offset;
			
			*size = 0;
			
			// Attempt to read the length of the array and the array offset
			if (sscanf(size + 1, "%x", &arrlen) > 0 && sscanf(cur->offset + 1, "%x", &offset) > 0)
			{
				Name* nn = 0;
				int i;
				
				// Create a node for each element of the array
				for (i=0;i<=arrlen;i++)
				{

Look at "for (i=0;i **<=** arrlen;i++)" instead of "for (i=0;i **<** arrlen;i++)". Is it correct behavior? Documentation says that array size after "/" must be equal to array size.

**Comment by owomomo** [comment]
The arry size after '/' should be consistent with the actural size, so I think `i <= arrlen` is a programming mistake. Maybe it's someone found a crash bug but fixed it with the wrong place?
