### ISSUE TITLE
PPU Memory - manual writes to $3F0C issue

### ISSUE THREAD

**Issue by cyneprepou4uk** [TASVideos/fceux#285]
Started from [1.0.385](https://ci.appveyor.com/project/zeromus/fceux/builds/35644369) version (1.0.384 was ok).

Writing to $3F0C or $3F1C affects $3F0A as well.

![gif](https://i.imgur.com/6p9B6B3.gif)

**Comment by g0me3** [comment]
fixed in https://github.com/TASVideos/fceux/commit/ffd322424e62eb94cf9faedbca5f806fc5353892

**Comment by bbbradsmith** [comment]
Ah, thanks for finding that. Looks like I caused that bug. UPALRAM is already mirrored properly inherently and addressed differently, so my attempt to use 0x10| on the address was totally bogus. Even that should have been 0x10^ instead, if it had been addressed the way I was thinking. ;P (g0me3's fix is correct)
