### ISSUE TITLE
Found typo in state.cpp

### ISSUE THREAD

**Issue by Dwedit** [TASVideos/fceux#289]
Randomly found this typo:

```
	if(SPreSave) SPreSave();
	totalsize+=WriteStateChunk(os,0x10,SFMDATA);
	if(SPreSave) SPostSave();
```
It's comparing the wrong pointer before calling SPostSave.

**Comment by mjbudd77** [comment]
I agree, this is wrong. I will fix it

**Comment by mjbudd77** [comment]
This issue has been fixed in the commit referenced above.
