### ISSUE TITLE
[FreeBSD] Loading a FDS rom while playing a NES rom crashes the emulator.

### ISSUE THREAD

**Issue by TCH69** [TASVideos/fceux#306]
After the #303 issue was solved, I tried to play some games on the new version. But it often crashes, most when loading a FDS rom while playing a NES rom. It also generated a dump (.core) file, and here is what it says:
```
Process 34704 stopped
* thread #6, name = 'fceux', stop reason = signal SIGSEGV: invalid address (fault address: 0x2d441a00)
    frame #0: 0x00552e6b fceux`Blit8ToHigh(unsigned char*, unsigned char*, int, int, int, int, int) + 5339
fceux`Blit8ToHigh:
->  0x552e6b <+5339>: movl   (%edi,%edx,4), %ecx
    0x552e6e <+5342>: movl   -0x10(%ebp), %edx
    0x552e71 <+5345>: movl   %ecx, (%edx)
    0x552e73 <+5347>: addl   $0x4, %edx
```
According to the FreeBSD Handbook, "```SIGSEGV``` indicates that the program tried to access memory (run code or read/write data usually) at a location that does not belong to it, but does not give any specifics.". So how can I fix it and stop the emulator from crashing and crashing?

**Comment by mjbudd77** [comment]
Can you provide the rom files and give me a procedure to reproduce the issue?

**Comment by TCH69** [comment]
The FDS rom I tried is the All Night Nippon Super Mario Bros. rom and the NES rom is the Super Mario Bros.  rom.
First, I open the SMB rom, then open the ANNSMB rom, it crashes right away. Loading the ANNSMB rom first also crashes the emulator. I was seeing quite a lot of warnings in the compilation process, but I think they were just unused variables.

**Comment by mjbudd77** [comment]
I have loaded both the games you are referring to and played each for a solid 10 minutes. I can't reproduce the crash. One difference in my setup is that I am running the x86_64 bit version of FreeBSD 12.2 in a virtual machine. I'm not sure how to proceed from here, I can't debug it if I can't make the issue occur.

**Comment by TCH69** [comment]
I've tried compiling it agian and the problem is fixed now, I think I'll close this issue now. Also, I can't stop the emulator from resizing automatically, even when the option is unchecked.

**Comment by mjbudd77** [comment]
Good to hear the issue is resolved. Also, the Apply button needs to be clicked after changing the state of anything on the video config window in order for the changes to take place.
