### ISSUE TITLE
"Auto scale on resize" option is not saved when closing the emulator.

### ISSUE THREAD

**Issue by TCH69** [TASVideos/fceux#311]
I haven't experience this error on the GTK3 build, only on the Qt build yet. The option is not saved by the emulator, even when the "Apply" button is clicked. It appears that there's an option named "AutoScale" in fceux.cfg, changing it to 0 doesn't fix the problem.
Below is the video I recorded while reproducing the error.
https://user-images.githubusercontent.com/44942508/105607009-f7faff80-5dce-11eb-95cb-4f8d3ff4f79e.mp4

**Comment by mjbudd77** [comment]
I have made a couple commits to the Qt GUI that I think will fix your issue. Please confirm.

**Comment by TCH69** [comment]
It works perfectly fine now, thanks!
