### ISSUE TITLE
[Feature Request] Add the ability to bind load and save state to gamepad

### ISSUE THREAD

**Issue by r57zone** [TASVideos/fceux#312]
Hi, it would be great to see support for add the ability to bind load and save state to gamepad, so that we can not use third-party software to emulate buttons to save and load state.

![](https://user-images.githubusercontent.com/9499881/106366277-2723ea80-6354-11eb-86d2-f34d25f3ac0c.png)

Thank you for your cool program.

**Comment by bbbradsmith** [comment]
Given how the implementation for gamepads already works, I'm a little surprised the hotkeys assignment doesn't also listen to gamepads? I agree this would be a good feature. (It wouldn't go on the gamepad setup page, like you've shown a picture of, but in the hotkeys settings instead.)

**Comment by r57zone** [comment]
Yes, it looks like only the keyboard works there.
Nes games are quite complex and I think most of the players are forced to use saves, so it might make sense to also add this setting to the gamepad menu, since it seems that this is one of the basic functions.

**Comment by g0me3** [comment]
as for me, much more convenient would be fast forward button bind for gamepad. but indeed. hotkey binding to pads as well will be enough to any request ;)

**Comment by KOT040188** [comment]
> as for me, much more convenient would be fast forward button bind for gamepad. but indeed. hotkey binding to pads as well will be enough to any request ;)
When can we expect this to happen?

**Comment by mjbudd77** [comment]
I have come up with a way to remap game pad buttons to key sequences in the Qt version of the gui. The way it would work is by programatically generating keyboard events and pushing onto the main application event queue when the desired game pad buttons are pressed. This capability would allow for any menu shortcut or gui hot key to be triggered from a remapped game pad button. I can even go as far as having separate key sequences be triggered on button press and release. I have also been kicking around an idea to have buttons on the gamepad act as modifiers (similar to shift, alt, and ctrl key behaviors) to expand the number of functions that can be mapped to buttons on the game pad. For example, holding the L or R button down on an SNES style controller can cause the mappings for the x,y,a,b buttons to do something different when pressed. Feedback on these ideas would be most appreciated.

**Comment by mjbudd77** [comment]
My first implementation of this functionality now exists in the Qt GUI. Give it a try.

**Comment by r57zone** [comment]
The rewind button would also come in handy on a gamepad button

**Comment by ClusterM** [comment]
> My first implementation of this functionality now exists in the Qt GUI. Give it a try.

I tested Windows Qt build and I can't bind any function to the gamepad.

**Comment by mjbudd77** [comment]
Can you give me an example of how you tried to set it up? I don’t think it works the same way you have it on the win32 version. You have to go to the advanced menu on the game pad config window and setup a game pad button to generate a key sequence when pressed. That key sequence needs to match the hot key you want to trigger

**Comment by ClusterM** [comment]
@r57zone any feedback?

**Comment by r57zone** [comment]
@ClusterM Works, thanks a lot
