### ISSUE TITLE
[Feature Request] Support for Arduino Light Gun

### ISSUE THREAD

**Issue by r57zone** [TASVideos/fceux#313]
Hi, it would be great to see comport read support for Arduino Light Gun emulation.

Can read 2 bits, one will be responsible for the photodiode, and the second for pressing.

This will allow we to make super cheap pistols, as well as use the current ones without powerful microcontrollers like teensy.

It will be a bit slower than with the [USB gamepad emulation](https://github.com/TASVideos/fceux/issues/130) [[2]](https://github.com/TASVideos/fceux/pull/133), but it's still cool.

Thanks for cool program.

**Comment by bbbradsmith** [comment]
I don't understand how what you've described is any different than #130 you linked?

**Comment by r57zone** [comment]
The difference is that reading takes place directly through the virtual comport emulated by Arduino, without emulating a usb joystick

**Comment by bbbradsmith** [comment]
The zapper inputs from #130 can be mapped to any keyboard key or gamepad button.

So, either you can map your arduino light gun to one of those, and we already have support via #130, or you're asking for someone to write generic direct input support for some sort of arduino light gun device? The latter seems very impractical to me. Why can't you just output the arduino signal as a gamepad button?

**Comment by bbbradsmith** [comment]
Are you talking about this thing?

https://www.instructables.com/DIY-Arduino-Powered-IR-Light-Gun/

This works as a mouse, and would already work with the existing mouse as zapper input system.

**Comment by r57zone** [comment]
If make an emulation of the joystick, then probably the speeds will not fit, the processing will be completed before the value of the photodiode is read. Reading from comport requires a slightly longer delay (black screen -> white square, 115200).

This will allow to make a super cheap Zapper (photodiode + button + cheap arduino nano ch340).
![gun](https://cloud.githubusercontent.com/assets/9499881/13745843/ab66da74-ea09-11e5-9262-6c63f979f8a0.png)

**Comment by bbbradsmith** [comment]
Oh, no that is not possible at all. See the discussion for #130 but an emulator like this cannot possibly deliver low enough latency to make that work with existing zapper games. That's entirely the reason why the solution used for #130 was taken, because it could be done with hacked/new games designed around the latency.

**Comment by r57zone** [comment]
It turned out that can connect a [light gun via Digispark](https://github.com/r57zone/Zapper-Light-Gun-PC). Maybe it will be useful to someone who stumbles upon this.

**Comment by Boojakascha** [comment]
> Oh, no that is not possible at all. See the discussion for #130 but an emulator like this cannot possibly deliver low enough latency to make that work with existing zapper games. They need per-scanline precision of the sensor, not per-frame, and we will NEVER be able to output individual scanlines in this emulator like that. That's entirely the reason why the solution used for #130 was taken, because it could be done with hacked/new games designed around the latency.
> 
> If you want that to work, you will need a hardware emulator like the MiSTer, and a CRT to use it with. FCEUX can't do this.

While this is closed and I don't want to push too much, I would like to mention that the Zapper is in fact not a raster scanning gun (in all games but two) and that I am using FCEUX with non patched ROMs.
