### ISSUE TITLE
Is the PAL filter adjustment finished and usable?

### ISSUE THREAD

**Issue by owomomo** [TASVideos/fceux#321]
The PAL adjusting sliders in Pallete dialog are always keep disabled, and I found nowhere in the code to enable them, but the related variables seems ready in the code. 
Is it an unfinished feature that someone left in half, or it is already finished but forget to write the enabling code?

**Comment by vadosnaprimer** [comment]
I've been working on it for a while and never figured out how to simulate a lowpass filter, so it's unfinished. I'm not planning to work on it. If you want to see how it looked, check out the last commit before I disabled it.

**Comment by eugene-s-nesdev** [comment]
PAL-filter enabled again, you can use and enjoy it. 
But notice that it requires keep hardware acceleration (linear interpolation) enabled for best-looking.

Win32-build does hardwre acceleration / linear filter via Direct Draw. 
Recent Nvidia and AMD video drivers doesn't have full direct draw support, intel GMA/HD graphics does.

**Comment by vadosnaprimer** [comment]
https://github.com/TASVideos/fceux/commit/c2606a54cf77a05cb900c3e50961a48a37e551a7
