### ISSUE TITLE
Configuring emulator functions for gamepad buttons

### ISSUE THREAD

**Issue by KOT040188** [TASVideos/fceux#328]
I love this emulator.  Thanks to its author.  But one setting is missing.  I would like to customize functions such as save / load, screenshot, pause, reset and others on the gamepad buttons.

**Comment by g0me3** [comment]
Duplicate of #312

**Comment by mjbudd77** [comment]
As stated in #312, I have added some game pad to hot key mapping functionality to Qt GUI. I have not yet received any feedback on this.

**Comment by ClusterM** [comment]
@KOT040188 Can you provide any feedback?
