### ISSUE TITLE
FCEUX-QT: emulator don't remember Dendy mode

### ISSUE THREAD

**Issue by eugene-s-nesdev** [TASVideos/fceux#335]
Lastest FCEUX-QT commit broke Dendy-mode remember. It cancel every time when you're load NTSC-rom
and every time when you're press "Reset" being in Dendy-mode.
Dendy-mode, as Famiclone, was designed to run NTSC games at 50 FPS but keep NTSC-like CPU/PPU timings.

FCEUX-win32 logic is correct, you can repeat it in FCEUX-QT:
```
if user set "NTSC-mode" - NTSC-games runs in NTSC, and emulator remember it
if user set "Dendy-mode" - NTSC-games runs in Dendy, and emulator remember it too.
but when PAL-game is loaded, emulator switch to PAL automatically, until you're load NTSC rom.
```

Or you can make Auto-mode:
```
if "Auto-mode" set:
NTSC-games runs in NTSC-mode, PAL-games in PAL-mode, like FCEUX-QT works now 
```
otherwise Region need be Forced:
```
if "NTSC-mode" set:
NTSC-games runs in NTSC-mode, PAL-games in NTSC-mode
if "PAL-mode" set:
NTSC-games runs in PAL-mode, PAL-games in PAL-mode
if "Dendy-mode" set:
NTSC-games runs in Dendy-mode, PAL-games in Dendy-mode
```

I guess moving Region Selector to
` "emulation" -> "region" ` instead of
` "options" -> "video config" -> "region"` are good idea too.
It will be more clear and more close to FCEUX-win32 and other popular emulators (Mesen/puNES etc)

Also, FCEUX-win32 have correct logic to play FDS and NSF when dendy-mode set.

**Comment by mjbudd77** [comment]
Thank you for ideas and spelling out how it needs to work. I just pushed a commit that I think will fix this. Please confirm.

**Comment by eugene-s-nesdev** [comment]
Thank you, region selector logic works like FCEUX-win32 for now. Exactly as needed.
