### ISSUE TITLE
Understanding return values with memory read functions

### ISSUE THREAD

**Issue by kulbhushanchand** [TASVideos/fceux#337]
Hi,

I am reading a single byte from a RAM location (dec `134`, which holds value of `40`) via three different functions. 
As per the [lua function list](https://fceux.com/web/help/LuaFunctionsList.html) -
- `memory.readbyte(int address)` - Returns as a byte
- `memory.readbytesigned(int address)` - Returns as a byte
- `memory.readbyteunsigned(int address)` - Returns as a byte
- `memory.readbyterange(int address, int length)` - Returns as a string.

So, I checked the received data in MATLAB, and got following results - 

**Function**|**LUA console (print)**|**Number of bytes transferred**|**MATLAB**
:-----|:-----:|:-----:|:-----:
memory.readbyte(134)|40|2|5248
memory.readbytesigned(134)|40|2|5248
memory.readbyteunsigned(134)|40|2|5248
memory.readbyterange(134,1)|(|1|40

**Doubts** 
- Why the `return as byte` is transferred as separate bytes and `return as string` is transferred as single byte?
- It looks like for the same effect, the `memory.readbyterange` function is efficient because it uses lesser bytes transferred? 

Thanks.

**Comment by vadosnaprimer** [comment]
How exactly do you transfer them though? As a string?

**Comment by kulbhushanchand** [comment]
via TCP/IP connection
```
function GetData()
    local pos = memory.readbyte(134)
    print(pos)
    sock:send(pos)
end
```

**Comment by vadosnaprimer** [comment]
If you send "40" as an ASCII string then you obviously send 2 bytes. Indeed your best bet is passing over the binary buffer that comes out of `byterange`. That way your data won't look sensible if you print it **as** a string directly, but now each byte holds an entire byte of information (as opposed to just printable chars).

**Comment by kulbhushanchand** [comment]
Yes, that's why for reduced overhead I'm using `byterange`. 
Why `memory.readbyterange` is encoded in a way to send the entire byte as once as oppose to other functions? 
Isn't it inefficient for other functions to send a `byte` size info in 2 `bytes`

**Comment by vadosnaprimer** [comment]
Because it utilizes a cool feature of lua where it can send true binary buffer as a string. If you binary-dump such a buffer to a file, you'll get all the underlying bytes if you then open it in a hex editor.

```lua
function log(your_string_buffer)
    local logfile = io.open("file.txt", "wb")
    logfile:write(s)
    logfile:close()
end
```

We (fceux users) don't transfer data around too often, we usually just draw strings on the screen, so it's easier to work with regular strings. But representing raw bytes is better in raw byte form whenever someone needs that explicitly, like you do.

**Comment by kulbhushanchand** [comment]
Ahh, that clears the doubt.  
Thanks for the help.
