### ISSUE TITLE
Hiding cursor / menu on fullscreen (Linux)

### ISSUE THREAD

**Issue by polsvoice** [TASVideos/fceux#338]
Is it possible to hide the mouse cursor and menu while in fullscreen mode? According to the Help files, there's an option to do this in the Config menu, but I don't have a Config menu. I've looked through all of the menus, and I can't find it. I dug through fceux.cfg, and I couldn't find an option there, either. I tried changing the value of SDL.ToggleMenu, but that didn't seem to do anything, either. I'm using 2.3.0 on Linux.

**Comment by mjbudd77** [comment]
I added the menu hide functionality after the 2.3.0 release was made. You will have to build the latest source from this repo if you want that functionality. I will add something to make it possible to hide the cursor in the main viewport.

**Comment by keithbowes** [comment]
The old 2.2.3 release had a --nogui command-line option (useful for both playing without menus and in fbcon (kmsdrm in SDL 2)), but that option seems to cause nothing to work (the ROM not to load in the QT version; the GTK version at least silently quits) in 2.3.0.  Maybe mjbudd77's new functionality makes the 2.3.x series catch up with the 2.2.x series in that regard.

**Comment by mjbudd77** [comment]
Added cursor hide functionality in commit b1c0c44.

**Comment by mjbudd77** [comment]
This should be fixed, please evaluate and close if satisfactory

**Comment by polsvoice** [comment]
Works great! Thank you!
