### ISSUE TITLE
Can't change frameskip through Lua

### ISSUE THREAD

**Issue by rafaelcp** [TASVideos/fceux#34]
There is no Lua command to change frameskip at runtime. At least I could not find it in documentation nor in source code. I'm running some AI experiments and I'd like to add frameskip while in nothrottle mode and set it to 0 while in normal speed.

**Comment by zeromus** [comment]
emu.speedmode
"normal" "nothrottle" "turbo" "maximum"

**Comment by rafaelcp** [comment]
I'm still having the same issue on linux after the patch, can't get maximum FPS on nothrottle without setting --frameskip 60 in command line. Also, in this case, it doesn't go back to 0 frameskip if I change speedmode to normal. Videos: https://imgur.com/a/T6Y4vyi

**Comment by zeromus** [comment]
the linux version is garbage and I don't support it. I can't personally guarantee anything about what happens when it comes to lua scripts altering how the frontend presents frames. I'm not surprised it's broken. Use the windows version in wine if you want something that works.
