### ISSUE TITLE
[FCEUX-QT/Request] Aspect Ratio box

### ISSUE THREAD

**Issue by eugene-s-nesdev** [TASVideos/fceux#341]
Can you add TV Aspect Ratio selector like win32-port has?

![aspect](https://user-images.githubusercontent.com/13199529/111885062-88704d80-89d6-11eb-8f8f-e2c0be992fa3.png)

Or maybe you prefer mesen-style:

![mesen](https://user-images.githubusercontent.com/13199529/111885178-2bc16280-89d7-11eb-959d-cde7823bcdc8.png)

**Comment by eugene-s-nesdev** [comment]
Fresh sources give compilation errors:

System:    
Host: i7-2600K Kernel: 5.4.0-54-generic x86_64 bits: 64 compiler: gcc v: 7.5.0 
Desktop: Cinnamon 4.4.8 wm: muffin dm: LightDM Distro: Linux Mint 19.3 Tricia 
base: Ubuntu 18.04 bionic 

[buildlog.zip](https://github.com/TASVideos/fceux/files/6177370/buildlog.zip)

**Comment by mjbudd77** [comment]
Just made another commit that should help your build issue.

**Comment by eugene-s-nesdev** [comment]
Ok, thank you, it works now

**Comment by eugene-s-nesdev** [comment]
BTW, bb10dark and bb10light themes works incorrect (wrong colors/sizes) on this desktop environment:
![test](https://user-images.githubusercontent.com/13199529/111906111-10e70080-8a60-11eb-8d43-5fed3e5fa8de.png)

All other GUI themes works good.

**Comment by mjbudd77** [comment]
The base style themes are loaded as dynamic libraries from the OS environment. Unfortunately, there is nothing that I can change in fceux that will make it look any better. The list of styles is the full list of installed styles available to Qt. All I can say is don’t use the ones that look bad.

**Comment by mjbudd77** [comment]
Are the aspect ratio changes working like you expect? I still plan to add custom aspect entry functionality later

**Comment by eugene-s-nesdev** [comment]
Looks like it have some inaccuracy compared to fceux-win32:

horizontal view:
![121](https://user-images.githubusercontent.com/13199529/111907441-59092180-8a66-11eb-9770-4d4b4af4126a.png)

vertical view:
![221](https://user-images.githubusercontent.com/13199529/111907454-6e7e4b80-8a66-11eb-9674-cc7df7b00bf5.png)

**Comment by eugene-s-nesdev** [comment]
[testroms.zip](https://github.com/TASVideos/fceux/files/6177576/testroms.zip)

**Comment by mjbudd77** [comment]
Thank you for the test ROMs. They were most helpful. I think I got it matching the win32 version now. Please test my latest commit 95aa96a.

**Comment by eugene-s-nesdev** [comment]
Looks good, thank you.
BTW, another bug: if you map "right shift" (to select for example) it will shown as "left shift" in GUI

**Comment by mjbudd77** [comment]
Qt treats shift as a modifier key, you shouldn’t map game pad buttons to it.
