### ISSUE TITLE
.fceux files not named correctly on macOS

### ISSUE THREAD

**Issue by tpwrules** [TASVideos/fceux#343]
The files intended to be saved in the directory `~/.fceux` are not named correctly by the latest master build on macOS 11.2.3 (not tested any other verisons).

It seems fceux is passing a path to a function that expects a file. For example, the SRAM file for `mario.nes` is supposed to be saved in the file `mario.sav` in the directory `~/fceux/sav`. However, it is actually saved in the file named `~/.fceux:sav:mario.sav` because fceux tries to save to the file (not path!) `~/.fceux/sav/mario.sav` and macOS converts the `/` to `:` for legacy reasons. This seems to be a problem for all the directories and files under `~/.fceux`, with the exception of `fceux.cfg` which gets saved in the `~/.fceux` directory as expected.

**Comment by mjbudd77** [comment]
This should be fixed now. Please verify

**Comment by tpwrules** [comment]
This is fixed. Thank you!
