### ISSUE TITLE
"Super Mogura Tataki!!" | Set Input for bad dump (CRC32)

### ISSUE THREAD

**Issue by infval** [TASVideos/fceux#344]
https://github.com/TASVideos/fceux/blob/5f1263aef31d9dc1ce1f55e6bfd275b908e41944/src/ines.cpp#L200
CRC32: C7BCC981 - good dump
CRC32: 9F8F200A - bad (old) dump
Information:
https://datomatic.no-intro.org/index.php?page=show_record&s=45&n=2162
http://bootgod.dyndns.org:7777/profile.php?id=4686
CRC can be added or replaced. I think the addition is better.

**Comment by ClusterM** [comment]
Added. Thank you!
