### ISSUE TITLE
Ayuda admins!

### ISSUE THREAD

**Issue by rodrigomiliano** [TASVideos/fceux#346]
Hola! estoy intentando implementar algo para mi proyecto de carrera de analista de sistemas de la materia integracion tecnologica.
Su proyecto me interesa, deberia solamente aplicarle un pequeño agregado, nose si podrìan guiarme:

- debo agregar un boton que cumpla la funcion como si se estuviesen apretando 2 al mismo tiempo (ejemplo: A+B)

¿Podrian ayudarme?
Muchas gracias.

**Comment by bbbradsmith** [comment]
Please don't use github to ask for help with your homework.
