### ISSUE TITLE
wrong buffer length check for strcpy

### ISSUE THREAD

**Issue by Dushistov** [TASVideos/fceux#348]
Here https://github.com/TASVideos/fceux/blob/18c7c95ef3b0ab97839f928a09d2ffa81f9e67ef/src/asm.cpp#L19 

Before call strcpy there is check that argument `str` fit to buffer,
but for some reason the constant not 127, but 0x127, which is  295:
```
char astr[128];
if ((!len) || (len > 0x127)) return 1;
strcpy(astr,str);
```

**Comment by mjbudd77** [comment]
Fixed in commit 9fc0237a.
