### ISSUE TITLE
Problems loading lua script on windows

### ISSUE THREAD

**Issue by IgnacioCVGitHub** [TASVideos/fceux#355]
Hello everyone. I'm trying to launch a really simple lua script to test the command line options for windows. However, when I execute the following command

> fceux64 -lua test.lua

, the simulator launches but it only shows a black screen. Therefore, I have to launch manually the script from File-> Lua -> New Lua script window.

The script is as simple as this (don't pay attention to indentation):
`emu.poweron()`
`emu.loadrom("rom.nes")`
`movie.play("movie.fm2")`
`while true do
    emu.frameadvance()
end`

I'm certain that the code itself works because the emulator runs it with no issues. However, it bothers me that it can't lauch itself from the command line in windows. Does anyone know why this happens? Is there a way to solve it? Am I doing something wrong? Is that the way it's supposed to work when you run the -lua option in the command line?

Thanks a lot. Have a nice day!

**Comment by ClusterM** [comment]
Hi!
You need to load any ROM on startup to execute Lua script. The `emu.loadrom()` function is to switch ROM only:

```
emu.poweron()
movie.play("movie.fm2")
while true do emu.frameadvance() end
```

```
fceux64 -lua test.lua rom.nes
```

**Comment by IgnacioCVGitHub** [comment]
Hi there! 

I tested your feedback and it works perfectly. Thanks a lot for your help, sir.
