### ISSUE TITLE
emu.speedmode("turbo") vs emu.speedmode("maximum")

### ISSUE THREAD

**Issue by ClusterM** [TASVideos/fceux#356]
Seems like there is no documentation on `emu.speedmode()` modes.

Why `emu.speedmode("turbo")` is faster than `emu.speedmode("maximum")`? Is it normal?

Also `emu.speedmode("turbo")` runs ROM without sound while `emu.speedmode("maximum")` runs with cracking sound and without video (black screen).

```
emu.poweron();
emu.speedmode("turbo");
while (emu.framecount() < 10000) do
  FCEU.frameadvance();
  emu.print("Frame #"..tostring(emu.framecount()));
end;
emu.exit();
```
Executed in 27 seconds. No sound.

```
emu.poweron();
emu.speedmode("maximum");
while (emu.framecount() < 10000) do
  FCEU.frameadvance();
  emu.print("Frame #"..tostring(emu.framecount()));
end;
emu.exit();
```
Executed in 33 seconds. No video.

Tested on Windows.

Seems like `emu.speedmode("maximum")` is slower because of sound. But why `emu.speedmode("turbo")` runs without sound and `emu.speedmode("maximum")` runs without video? Is it a bug or a non-documented feature?

**Comment by zeromus** [comment]
This isn't anything but a big mess. Someone added the maximum feature to skip as much video work as possible, but they didnt realize there was an option for turbo to skip audio optionally, so maximum doesnt have an audio-skipping feature. Someone else wrote this:

> Turbo and max speed are two different results. Turbo employs frame skipping and sound bypassing if mute turbo option is enabled. This makes it faster but with frame skipping. Therefore, maximum is still a useful feature, in case the user is recording an avi or making screenshots (or something else that needs all frames)

I dont really know what that means.

I suggest you mute the audio and use whichever option runs faster for you.

**Comment by ClusterM** [comment]
Actually I'm using it to record screenshots and "maximum" works too. It can capture screenshot even emulator shows black screen. But "turbo" mode is faster and without annoying sound, so it's better for me. Thank you.

**Comment by eugene-s-nesdev** [comment]
That's bad GUI "speed" drop-down menu don't have "fastest speed" option.
You can access it via mapping hotkey only

![asa](https://user-images.githubusercontent.com/13199529/122621346-eb3cb800-d09d-11eb-9117-7c46af2bd6f6.png)
