### ISSUE TITLE
Linux fails to compile as of latest commit

### ISSUE THREAD

**Issue by retro-wertz** [TASVideos/fceux#36]
/bin/ld: src/fceu.o: in function `FCEUI_LoadGameVirtual(char const*, int, bool)':
/mnt/data/dev/fceux/src/fceu.cpp:421: undefined reference to `archiveManuallyCanceled'
collect2: error: ld returned 1 exit status
scons: *** [src/fceux] Error 1
scons: building terminated because of errors.

issue started here: https://github.com/TASVideos/fceux/commit/5eb6cc31c9a28a0cbaf5897a3e1f58f71d8b2d1f#diff-87958eb3baaa0d33eb8a1fcf168572a4

seem like **archiveManuallyCanceled** was something done for the windows gui only...

**Comment by zeromus** [comment]
fixed by e72202f3b86643077a73a2c75b8465ca1300c4f5
