### ISSUE TITLE
[win32] Updated icon for 2.4.0 release

### ISSUE THREAD

**Issue by eugene-s-nesdev** [TASVideos/fceux#362]
Current win32 build have old, lowres and ugly icon, that looks outdated:

![test_01](https://user-images.githubusercontent.com/13199529/120896131-d2a5ba00-c628-11eb-99cd-905db7535a9b.png)

Here is a new icon by Terwilf: https://www.deviantart.com/terwilf/art/Ic-Fceux-HQ-564917857
I converted it to *.ico contains: 16x16, 24x24, 32x32, 48x48, 64x64, 96x96, 128x128, 256x256 sizes.
(if it contains too much resolutions, i can reduce it, if need. Current icon size is 64,9 Кbytes)

![new](https://user-images.githubusercontent.com/13199529/120896290-93c43400-c629-11eb-8b18-b9e88f6ef682.png)

By the way, QT-build icon have white border, that looks not so good on dark themes:

![dark](https://user-images.githubusercontent.com/13199529/120896660-34ffba00-c62b-11eb-8a0a-fb19c33ee76a.png)

Icon + Original Source image by Terwilf
[HiRes_Icon.zip](https://github.com/TASVideos/fceux/files/6602748/HiRes_Icon.zip)

**Comment by mjbudd77** [comment]
The only reason I have the white around the icon and text is so that you can see it on really dark desktop backgrounds. I don’t mind using your new ico for the Qt windows application if this is what windows users want. I just know that I couldn’t see the icon on my Ubuntu desktop without adding some contrast

**Comment by mdinslage** [comment]
Agreed, the icon is nice, but without the white border it would virtually disappear on a dark background.

**Comment by ClusterM** [comment]
I added white stroke and converted it to .ico:
[icon.zip](https://github.com/TASVideos/fceux/files/6656839/icon.zip)

**Comment by ClusterM** [comment]
Preview:

![image](https://user-images.githubusercontent.com/4236181/122083768-d2b46f80-ce09-11eb-85d4-d7902eb2d040.png)

![image](https://user-images.githubusercontent.com/4236181/122083852-e8c23000-ce09-11eb-88e3-a081e7d8d7e8.png)

![image](https://user-images.githubusercontent.com/4236181/122083904-f8417900-ce09-11eb-9d17-4f3fc9269807.png)

![image](https://user-images.githubusercontent.com/4236181/122084023-14ddb100-ce0a-11eb-8211-488143d35bcd.png)

I'll create PR.

**Comment by mjbudd77** [comment]
I went to the link above and noticed that there was a copyright statement. Do we have terwilf’s permission to copy his work?

**Comment by ClusterM** [comment]
> I went to the link above and noticed that there was a copyright statement. Do we have terwilf’s permission to copy his work?

Need to ask him.

![image](https://user-images.githubusercontent.com/4236181/122088349-4ce6f300-ce0e-11eb-8f5e-3400fa9db019.png)

I don't like how it looks in the taskbar. Increase stroke size maybe?

**Comment by ClusterM** [comment]
More white stroke.

![image](https://user-images.githubusercontent.com/4236181/122089774-c6331580-ce0f-11eb-92d0-8dc83dbc3e79.png)

**Comment by mjbudd77** [comment]
I’m assuming you are using something like magick to generate the lower resolution icons. If scaling from 256 to 32, you would need the white border to be at least 8 pixels wide in the 256 image

**Comment by mjbudd77** [comment]
Also, you may be splitting hairs here, at a glance it still looks pretty good

**Comment by ClusterM** [comment]
> I’m assuming you are using something like magick to generate the lower resolution icons. If scaling from 256 to 32, you would need the white border to be at least 8 pixels wide in the 256 image

I'm using Photoshop to add white stroke and magick to combine multiple png's to ico. Increased border, so it's ~9 pixels on 256x256 image.

**Comment by mjbudd77** [comment]
Try not to have too many iterations of this in git. Git is pretty inefficient and wasteful when tracking binary images

**Comment by ClusterM** [comment]
> Try not to have too many iterations of this in git. Git is pretty inefficient and wasteful when tracking binary images

Oh, the "squash and commit" option is disabled for this repo... I have not noticed it before, sorry.

**Comment by ClusterM** [comment]
Current version.

[icon3.zip](https://github.com/TASVideos/fceux/files/6657276/icon3.zip)

**Comment by mjbudd77** [comment]
Who is taking the task of reaching out to terwilf for permission?

**Comment by eugene-s-nesdev** [comment]
ClusterM taking this task

**Comment by ClusterM** [comment]
> Who is taking the task of reaching out to terwilf for permission?

I already asked him on DeviantArt and Twitter, waiting for a reply.

**Comment by ClusterM** [comment]
Terwilf gave his permission: https://twitter.com/Cluster_M/status/1404845822412472323

By the way, who is the author of the icon used for .deb package? https://github.com/TASVideos/fceux/blob/master/fceux1.png
It looks totally the same but with a terrible border.

And this one: https://raw.githubusercontent.com/TASVideos/fceux/master/icons/fceux.ico
Replace it with the same multisize icon maybe?
E.g. move "src/drivers/win/res/ICON_1.ico" to "icons/fceux.ico" and change https://github.com/TASVideos/fceux/blob/e1f67a0a86c2c87cb9f3fe67f9103fcd74463059/src/drivers/win/res.rc#L2358
to "../../../icons/fceux.ico"

**Comment by ClusterM** [comment]
Tried the Qt version with a new icon. Comparison:

![image](https://user-images.githubusercontent.com/4236181/122138521-9441a380-ce4f-11eb-83ca-11e7eb4f9c59.png)

**Comment by mjbudd77** [comment]
I will just replace the icon for Mac OS and Linux with the one you have. Can you replace the fceux1.png icon with the 512x512 png that you have?

**Comment by ClusterM** [comment]
> I will just replace the icon for Mac OS and Linux with the one you have. Can you replace the fceux1.png icon with the 512x512 png that you have?

Done.
