### ISSUE TITLE
[core] "force grayscale" overrides by emphasis bits

### ISSUE THREAD

**Issue by eugene-s-nesdev** [TASVideos/fceux#363]
Set palette -> "force grayscale" to play in black'n'white mode. 
It works good until game use emphasis bits:
https://youtu.be/HgvguRyi_-0

**Comment by ClusterM** [comment]
It's because `SetPaletteBlitToHigh()` function uses `color_palette` array only for base 64 colors and `palo` array for full size deemph palette while grayscale filter applied to color_palette only.

**Comment by ClusterM** [comment]
Fixed.
