### ISSUE TITLE
Win64 interim builds contains 7z.dll instead of 7z_64.dll

### ISSUE THREAD

**Issue by ClusterM** [TASVideos/fceux#367]
Seems like there is an error in the file https://github.com/TASVideos/fceux/blob/master/pipelines/win64_build.bat

It adds `..\src\drivers\win\7z.dll` file to archive but it should use `..\src\drivers\win\7z_64.dll`. 7-zip support is broken in Win64 interim builds.

**Comment by bbbradsmith** [comment]
Does https://github.com/TASVideos/fceux/commit/6be59b2d8d44d20ced73ed29c83b51cb748943b7 fix it?

**Comment by ClusterM** [comment]
Yes, the latest automatic build contains 7z_64.dll and works great now.
