### ISSUE TITLE
Cannot Find Screenshots Folder

### ISSUE THREAD

**Issue by glow12121** [TASVideos/fceux#369]
Hi,

Many thanks for having made this emulator. I am enjoying Battle City (Tanks) I used to play on Dandy as a child.

I have this issue - I cannot find the folder where FCEUX saves screenshots. I've looked everywhere I could and still don't see them. I installed FCEUX from repositories of Solus Linux. The game ROM is stored in one of the `/home` subfolders.

**Comment by mjbudd77** [comment]
Screen shots for the Linux version of the emulator should be in $HOME/.fceux/snaps

**Comment by mjbudd77** [comment]
Pkgs.org shows a very old version of fceux for solus Linux. I recommend building the latest master branch of this repo from source. There has been many improvements since the 2.2.3 release

**Comment by glow12121** [comment]
Thanks! Found it.

I will ask on the Solus development forum to update, so everyone can enjoy the latest version.
