### ISSUE TITLE
[core] Scale 2x/3x filters: abnormal performance

### ISSUE THREAD

**Issue by eugene-s-nesdev** [TASVideos/fceux#375]
I've found strange issue while doing massive Win32/QT-testing on different hardware.
Long story short: Scale 2x and 3x filters are abnormally SLOW compared to other FCEUX filters.

One of my laptop(netbook) for testing is an Asus eeePC based on intel Atom N550 1500MHz (2C/4T).
It runs all avaliable FCEUX filters fullspeed, including most-heavy PAL3x too.
But "Scale 2x" runs at ~30FPS, Scale3x runs at ~15FPS.

This is VERY strange, because simple Scale2x/3x filters must be much faster than even hq2x filter.
I tested nestopia and virtuanes scale filters on this laptop, and it works like a charm.
- Atom at default 1500MHz: Nestopia + scale2x = ~240FPS no-throttle
- Atom at downclocked to 1000MHz: Nestopia + scale2x = ~150FPS no-throttle

I guess this is a core bug. It happens both on win32 and QT-versions.

**Comment by mjbudd77** [comment]
I do not have this issue on my laptop Intel i7-6700HQ CPU @2.60GHz. I get a steady 60 FPS on all filters.
When checking emulation thread CPU usage for the following filters:
prescale 2x = 38%
scale 2x = 48%
hq2x = 52%
scale 3x = 67%
hq3x = 56%

**Comment by vadosnaprimer** [comment]
I get ~500fps on pixelated filters and ntsc. 300-400fps on 2x scales, pal, and hq3x. Scale3x is 190fp. You machine is probably **too bad**.

**Comment by eugene-s-nesdev** [comment]
Atom N550 results. Old PPU. Low quality sound, 48KHz.
Speed = maximum (no throttle)

none - 212 FPS
hq2x - 78 FPS
Scale2x - 30 FPS
Ntsc2x - 120 FPS
hq3x - 63 FPS
Scale3x - 15 FPS
Prescale2x - 154 FPS
Prescale3x - 128 FPS
Prescale4x - 107 FPS
PAL3x - 55 FPS

**Comment by eugene-s-nesdev** [comment]
Regression appears between FCEUX 2.2.2 <->2.2.3
OldPPU, LQ-sound, 2x2 window size, HW-accel:
-----------------------
Filter      | 2.2.2 | 2.2.3  |
-----------------------
none      | 308   | 200
hq2x      | 96     | 79
Scale2x   | 183   | 30
NTSC2x  | 102   | 120
hq3x      | 91     | 72
Scale3x  | 121    | 15
------------------------

**Comment by eugene-s-nesdev** [comment]
Broken since r3226 https://sourceforge.net/p/fceultra/code/3226/
https://github.com/TASVideos/fceux/commit/3ad28715f73bf83289c81e7e3f85b6474a8a34d5

win32, builded via MSVS2010
[r3225-3226-win32.zip](https://github.com/TASVideos/fceux/files/6673041/r3225-3226-win32.zip)

**Comment by zeromus** [comment]
Scale2x works on 8bpp values. The deemphasis can't be applied beforehand. That means the deemphasis is applied to 4 or 9 pixels. the deemphasis function I made is crappy. I just made a commit to optimize it a bit. This is as good as it's going to get. I'll support potato computers or special effects but not special effects on potato computers.

**Comment by eugene-s-nesdev** [comment]
Do you tested it before push?
both qt and win32-version shows black or random colored screen after loading any ROM.

**Comment by zeromus** [comment]
of course I tested it. as much as possible with this mess of options and code. Can't repro your problems, except that it did crash (on purpose) for the 3x filters so I fixed that.

**Comment by eugene-s-nesdev** [comment]
New optimisation results:

```
----------------------------
Filter     | old  | new   |
Scale2x    | 30   | 90    |
Scale3x    | 15   | 30    |
----------------------------
```

**Comment by zeromus** [comment]
I'm glad it's improved. That's as good as I'm going to make it.

**Comment by eugene-s-nesdev** [comment]
Core i7-2600K in you're interested:
win32-x64
```
----------------------------
Filter     | old  | new   |
Scale2x    | 325   | 380    |
Scale3x    | 179   | 179    | (same)
----------------------------
```

**Comment by mjbudd77** [comment]
I made one more little efficiency change that may help this more

**Comment by zeromus** [comment]
oh yeah that probably speeded it up. for some reason I was only thinking about the <1> case in assuming it would all get inlined and forgot about the parameter cases on the scale2x/3x.

**Comment by eugene-s-nesdev** [comment]
Nice results.
win32-x64 build:

```
Atom N550 (stock frequency):
-----------------------------------------
Filter     | old  | zeromus | mjbudd77  |
Scale2x    | 32   | 81      | 100       |
Scale3x    | 16   | 33      | 45        |
-----------------------------------------

Core i7-2600K (stock frequency):
-----------------------------------------
Filter     | old  | zeromus | mjbudd77  |
Scale2x    | 325  | 380     | 530       |
Scale3x    | 179  | 179     | 312       |
-----------------------------------------
```

**Comment by vadosnaprimer** [comment]
Wow nice indeed!
