### ISSUE TITLE
[win32] Hotkeys naming messed-up

### ISSUE THREAD

**Issue by eugene-s-nesdev** [TASVideos/fceux#376]
1. Open "config" -> "map hotkeys" window.
2. Double-click to something, "Toggle Fullscreen" for example
3. You'll see that all descriptions in mapping window are totally messed-up

![hotkeys](https://user-images.githubusercontent.com/13199529/122669508-6ac5a680-d1c6-11eb-9d13-3c4dc78a4a2b.png)

**Comment by ClusterM** [comment]
Fixed.
