### ISSUE TITLE
Wrong Qt driver scaling while moving the window between Retina display and Non-Retina display

### ISSUE THREAD

**Issue by movsb** [TASVideos/fceux#377]
This is what is displayed on MacBook Pro Retina display:

<img width="256" alt="image" src="https://user-images.githubusercontent.com/5374525/122676138-2d393b80-d20f-11eb-9c1c-383296af0c51.png">

And this is what is displayed on an external display while I move the window from Retina to the external display:

![image](https://user-images.githubusercontent.com/5374525/122676187-77222180-d20f-11eb-89ef-3b683add16d9.png)

When I move it back to Retina, it gets back to normal.

The current video config at below ( I don't why the `Scale` is `2.00`, changing it to `1` doesn't help ):

![image](https://user-images.githubusercontent.com/5374525/122676305-2b23ac80-d210-11eb-8720-38e7102792cd.png)

I've read the code, I guess the cause is that the `devPixRatio` won't change after the program initialized, since it's always the primary screen. And it doesn't connect to `primaryScreenChanged` event.

<https://github.com/TASVideos/fceux/blob/655609079be7bdb016c98eeaf71fe5a217d32a58/src/drivers/Qt/ConsoleViewerGL.cpp#L75-L81>

I'm not familiar with Qt, tried my best to find the reason why.
Everything is good when I choose the `SDL` driver.

I'm using HEAD. 

Thank you.

**Comment by mjbudd77** [comment]
@movsb you are correct that it is a problem with the devPixelRatio being different between the displays. I added code to detect screen changes and re-setup the display accordingly in commit 2cc52f1. Please give it a try and let me know if it is fixed.

**Comment by movsb** [comment]
@mjbudd77 Problem fixed. Thank you so much!
