### ISSUE TITLE
Holding "SHIFT" disables keyboard buttons

### ISSUE THREAD

**Issue by themalu866** [TASVideos/fceux#378]
Playing on Windows 7 x64 and for some reason when I save by pressing SHIFT+F1 all buttons are disabled with the exception of F1, F2, F3 and so on.
That means if I'm playing a game and save by pressing shift+F1 it stops abruptly (walking, running, jumping, shooting) and it happens with all games.
I tested other buttons and it seems that this only happens while the SHIFT button is pressed.
And isn't because I messed with the settings, it happens with default settings.
And isn't because of my keyboard, I tested it on version 2.2.3 and it works fine.
![A](https://user-images.githubusercontent.com/42208976/122689254-a88ef300-d1f7-11eb-8db9-99c95daa22f2.png)

**Comment by PinguLinux** [comment]
i use shift for the button B so i need to get stuck in older versions because i mainly play super mario bros and B is for running

**Comment by ClusterM** [comment]
> Playing on Windows 7 x64 and for some reason when I save by pressing SHIFT+F1 all buttons are disabled with the exception of F1, F2, F3 and so on.
> That means if I'm playing a game and save by pressing shift+F1 it stops abruptly (walking, running, jumping, shooting) and it happens with all games.
> I tested other buttons and it seems that this only happens while the SHIFT button is pressed.
> And isn't because I messed with the settings, it happens with default settings.
> And isn't because of my keyboard, I tested it on version 2.2.3 and it works fine.
> ![A](https://user-images.githubusercontent.com/42208976/122689254-a88ef300-d1f7-11eb-8db9-99c95daa22f2.png)

Weird, can't reproduce it on the latest build. Will do more investigations.

**Comment by ClusterM** [comment]
> i use shift for the button B so i need to get stuck in older versions because i mainly play super mario bros and B is for running

It's other bug, I'll fix it.

**Comment by ClusterM** [comment]
@themalu866 do you mean that game controls stopped working **while** you **holding** shift? Or it's not working **after** shift is released?

**Comment by ClusterM** [comment]
@themalu866 @PinguLinux any feedback?

**Comment by themalu866** [comment]
The game controls stopped working while you holding shift.
But I tested the newest one and it's working fine now.
It started working on this version, I also tested the newest one and is working too.
![fc](https://user-images.githubusercontent.com/42208976/128288702-7a2f5ddb-f17d-42bf-814f-9a64d604fc12.png)
