### ISSUE TITLE
compatibility broken with older QT-5 versions (< 5.11.0)  after commit '0053a52929f80b9dc676c6163f7a852f119b4e92'

### ISSUE THREAD

**Issue by CJ-Abrams** [TASVideos/fceux#384]
Commit "[0053a52929f80b9dc676c6163f7a852f119b4e92](https://github.com/TASVideos/fceux/commit/0053a52929f80b9dc676c6163f7a852f119b4e92)" modifies "src/drivers/Qt/PaletteConf.cpp" introducing many calls to a _**`horizontalAdvance`**_ function, witch appears to be unsupported in QT5 lib. versions < 5.11.0 (in my case I have v.5.9.5 installed), preventing a complete compiling with the following errors:

```
src/drivers/Qt/PaletteConf.cpp: In constructor ‘PaletteConfDialog_t::PaletteConfDialog_t(QWidget*)’:
src/drivers/Qt/PaletteConf.cpp:195:57: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
  195 |  notchFrame->setMinimumWidth( notchFrame->fontMetrics().horizontalAdvance('2') * strlen(stmp) );

src/drivers/Qt/PaletteConf.cpp:208:67: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
  208 |  saturationFrame->setMinimumWidth( saturationFrame->fontMetrics().horizontalAdvance('2') * strlen(stmp) );

src/drivers/Qt/PaletteConf.cpp:221:65: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
  221 |  sharpnessFrame->setMinimumWidth( sharpnessFrame->fontMetrics().horizontalAdvance('2') * strlen(stmp) );

src/drivers/Qt/PaletteConf.cpp:234:63: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
  234 |  contrastFrame->setMinimumWidth( contrastFrame->fontMetrics().horizontalAdvance('2') * strlen(stmp) );

src/drivers/Qt/PaletteConf.cpp:247:67: error: ‘class QFontMetrics’ has no member named ‘horizontalAdvance’
  247 |  brightnessFrame->setMinimumWidth( brightnessFrame->fontMetrics().horizontalAdvance('2') * strlen(stmp) );

make[2]: *** [src/CMakeFiles/fceux.dir/build.make:3317: src/CMakeFiles/fceux.dir/drivers/Qt/PaletteConf.cpp.o] Error 1
make[2]: *** Attesa per i processi non terminati....
make[1]: *** [CMakeFiles/Makefile2:114: src/CMakeFiles/fceux.dir/all] Error 2
make: *** [Makefile:149: all] Error 2
```

In many other files that same function is instead introduced via a contitional pre-processing instruction like at "[src/drivers/Qt/GameGenie.cpp : line 114](https://github.com/TASVideos/fceux/blob/18c7c95ef3b0ab97839f928a09d2ffa81f9e67ef/src/drivers/Qt/GameGenie.cpp#L114)", but I don't know if that workaround can actually be used in the "PaletteConf.cpp" file aswell.

Thanks anyway for the attention and your work.

**Comment by mjbudd77** [comment]
Should be fixed by commit referenced above. Please verify.

**Comment by CJ-Abrams** [comment]
@mjbudd77 > Should be fixed by commit referenced above. Please verify.

I've just verified the mentioned latest commit "[a993487d139d9a0b78397a631125ff054078bcc3](https://github.com/mjbudd77/fceux/commit/a993487d139d9a0b78397a631125ff054078bcc3)" and source compiles perfectly now.

Thanks again for your work!
