### ISSUE TITLE
Input - Advanced Key Bindings not saved in config

### ISSUE THREAD

**Issue by radzix88** [TASVideos/fceux#385]
I've configured my gamepad/keyboard to use Advanced Key Binding but it isn't saved in config file.
Xubuntu 20.04.02, fceux 2.4.0-interim git
![1](https://user-images.githubusercontent.com/47605609/124637589-38849c00-de8a-11eb-967d-0bbaa0ad776e.png)
![2](https://user-images.githubusercontent.com/47605609/124637600-3b7f8c80-de8a-11eb-8c7f-031c7140c75a.png)
![3](https://user-images.githubusercontent.com/47605609/124637641-4c300280-de8a-11eb-9e12-c37f1dda849e.png)

**Comment by mjbudd77** [comment]
I have just added some code to save the advanced bindings to a profile with the rest of the normal game pad settings. Please test at latest dev commit 6b65d12.

**Comment by radzix88** [comment]
Thank you very much. Could you help me how can I test your fixes? Download file and replace it with old one? Sorry for noob question...

**Comment by mjbudd77** [comment]
If you used the deb file from the auto builds. Uninstall the old one and then install new one. Or you can just clone the git repo and build the master from source. Build instructions are in the readme file. Look at The Linux build script in the pipelines folder to see how to build the like the pipeline does.

**Comment by radzix88** [comment]
Key bindings are saved in file and also after computer reboot so this issue was fixed.
