### ISSUE TITLE
[OSX] Unable to load Dynamic Libraries 

### ISSUE THREAD

**Issue by GregoryCannon** [TASVideos/fceux#388]
I'm looking to use the LuaSocket library in my Lua script for FCEUX. It works on Windows as expected. However, on Mac I have been completely unable to get it to run.

Once I configure the socket files such that FCEUX finds them, it still fails due to an apparent inability to load dynamic libraries.

```
Lua thread bombed out: error loading module 'socket.core' from file '/usr/local/lib/lua/5.1/socket/core.so':
	dynamic libraries not enabled; check your Lua installation
stack traceback:
	[C]: ?
	[C]: in function 'require'
	...Cellar/fceux/2.4.0/share/fceux/luaScripts/socket.lua:13: in main chunk
	[C]: in function 'require'
	...r/fceux/2.4.0/share/fceux/luaScripts/socket/http.lua:11: in main chunk
	[C]: in function 'require'
	...ments/TetrisTrainer/src/server/fceux/stackrabbit.lua:1: in main chunk
```

How can I get it to load the socket library? I would also be okay with any alternative way to make HTTP calls from Lua (although I assume they'd all involve a dynamic library at some point).

(To be clear: FCEUX has no trouble finding the `.../socket/http.lua` file that's being required. But it seems to be not allowing itself to load an inner dependency of that file, core.so)

**Comment by mjbudd77** [comment]
Looks like the Mac OSX version internally compiling and linking lua but is not setting the proper compiler definitions to allow for enabling of plugins. I will look into this.

**Comment by mjbudd77** [comment]
Please try out the latest development build at commit 34e4e03. Let me know if it resolved your issue.

**Comment by GregoryCannon** [comment]
That did fix it, thanks!

(Unfortunately, LuaSocket is being extremely difficult and refuses to run properly. But FCEUX is doing its part at least.)
