### ISSUE TITLE
Pause hotkey isn't working

### ISSUE THREAD

**Issue by romhacking** [TASVideos/fceux#39]
If I get a breakpoint hit in debugger, or if I pause the game by pressing "step into" button in it, I'm not able to unpause emulator using "pause" hotkey after clicking at the main window. Something in this https://github.com/TASVideos/fceux/commit/fe64ca3771029b928da55c9b7bf2e217e6e55a5f version corrupts its function. The rest hotkeys seems to be ok, like "frame advance" or "open rom".

**Comment by zeromus** [comment]
youre 100% sure it was that revision, or you're guessing?

**Comment by romhacking** [comment]
> 
> 
> youre 100% sure it was that revision, or you're guessing?

I'm 100% sure. Previous https://github.com/TASVideos/fceux/commit/5a1e6c552a1d33b6aba7dc129679c941bfe1b5d0 doesn't have this issue, the rest of them do.

**Comment by zeromus** [comment]
no, c7710ae244e9c8b01c0247a04aa702c616906bcd  broke it
please confirm

@aquanull please investigate this.

**Comment by romhacking** [comment]
> please confirm

Yes, the hotkey workes again.
