### ISSUE TITLE
[Feature request] Add alternative button mapping for controller

### ISSUE THREAD

**Issue by radzix88** [TASVideos/fceux#391]
It will be nice when we could map alternative buttons of controller. I mean another button for:
A, B, Select, Start, Up, Down, Left, Right, TurboA, TurboB
Especially for Up, Down, Left and Right so we can map also cross and analog for moving.
Maybe this can be done with hotkeys menu (add A, B, Select.... etc. there)?

**Comment by mjbudd77** [comment]
Added alternate gamepad button bindings in commit da084fb1.  Before testing, it would be best to remove previous input binding files. The format of the files has changed slightly for this change and an old file may be improperly read. Let me know how this works for you.

**Comment by radzix88** [comment]
Works exactly how I've imagined.
