### ISSUE TITLE
Problems saving input configuration

### ISSUE THREAD

**Issue by ImpressionableRaccoon** [TASVideos/fceux#392]
My configuration changes and the joystick does not work after saving and loading.

![IMG_PixelCam_Plus_20210803_121019](https://user-images.githubusercontent.com/47372390/127951719-e4e73f7b-a133-4b53-ac8c-f104baf94c11.jpg)
![IMG_PixelCam_Plus_20210803_121045](https://user-images.githubusercontent.com/47372390/127951734-9743a7f8-d567-42b4-9333-b9d1566cf914.jpg)
![IMG_PixelCam_Plus_20210803_121110](https://user-images.githubusercontent.com/47372390/127951745-140048c7-d7d8-4f41-83be-c50873cd80d9.jpg)

**Comment by mjbudd77** [comment]
If you are trying to save input settings for a joystick, you should select the joystick in the device combo box. From the image you have the input device set to keyboard. You should not save joystick bindings to the keyboard profiles.

**Comment by ImpressionableRaccoon** [comment]
It works! Thanks :)
