### ISSUE TITLE
How to enable/disable BG/FG layers

### ISSUE THREAD

**Issue by hellocatfood** [TASVideos/fceux#403]
I have compiled fceux 2.4.0 (commit #74e3b815361d36db80e676f836a043baab1ac2a4 ) on Ubuntu 21.04 and I'm trying to find the options for enabling/disabling the background and sprite layers. In the manual it says it's under Config > Display https://fceux.com/web/help/ToggleSwitchesHideMenuetc.html but I don't have those options

![Screenshot from 2021-09-19 21-27-10](https://user-images.githubusercontent.com/151947/133942275-039b5fea-d412-4472-b67c-bbec519b4cdf.png)

In the Video Config menu I also can't see anything about disabling layers.

![Screenshot from 2021-09-19 21-27-26](https://user-images.githubusercontent.com/151947/133942280-c5aee690-e81c-4a0c-8973-4b01a29a626e.png)

Does this option not exist for linux versions of fceux?

**Comment by mjbudd77** [comment]
I believe there is a hot key for these

**Comment by hellocatfood** [comment]
@mjbudd77 do you know the hotkey for this?

**Comment by mjbudd77** [comment]
By default there are no key bindings assigned for these. Open the hot key config window. Find toggle object display and toggle background display. Bind a key to those functions and it should work.

**Comment by mjbudd77** [comment]
@hellocatfood , were you able to get this to work? Can this issue be closed?

**Comment by mjbudd77** [comment]
I tested this again myself. It works as I described above.
