### ISSUE TITLE
Support plain text configuration

### ISSUE THREAD

**Issue by crocket** [TASVideos/fceux#404]
I prefer plain text config to GUI config.

fceux supports only GUI config which writes every setting in ~/.fceux/fceux.cfg

I want to see documentation of text config options with their default values and override only some settings in ~/.fceux/fceux.cfg.

I also want to configure button mapping in plain text.

Retroarch supports it by documenting defalut values for every text config option in /etc/retroarch.cfg and allowing me to override default values in ~/.config/retroarch/retroarch.cfg. It also allows me to prevent retroarch GUI from writing to ~/.config/retroarch/retroarch.cfg.

**Comment by mjbudd77** [comment]
I'm not interested in re-writing the config system for this. The current system in place works good enough. All config parameters can be changed from within the GUI and saved.  If you want to save your configuration, just copy the file to a new name. If you want to return a value to its default value, just delete it from the file. To restore all values to their defaults, just delete the file all together.

**Comment by crocket** [comment]
Okay.
