### ISSUE TITLE
lua savestate.load broken

### ISSUE THREAD

**Issue by spiiin** [TASVideos/fceux#41]
I used latest fceux autobuild and tried to run simple lua script:
```
savestate.load(savestate.create(2))
```
It doesn't do anything (I created savestates in all slots for testing).

**Comment by spiiin** [comment]
Looks like this line is incorrect:
https://github.com/TASVideos/fceux/commit/4939859cf466530e7e5771b27074496ea2c605f0#diff-8bc66762cbe5d834c8a04828a38b06e6R2656
[luaL_checkstring](http://pgl.yoyo.org/luai/i/luaL_checkstring) converts integer argument to string and uses it as filename.

**Comment by zeromus** [comment]
fixed?
