### ISSUE TITLE
Tsuri Kichi Sanpei: Blue Marlin Hen - Unemulated feature

### ISSUE THREAD

**Issue by ReyVGM** [TASVideos/fceux#410]
I tried the game on Bizhawk (not the latest version), FCEUX, NesterJ, Nestopia, VirtuaNES, Messen and none emulate Tsuri Kichi Sanpei: Blue Marlin Hen correctly.

It's easy to replicate. Just start the game, press start to open the map, sail to the docks on the right (a square will light on), then press start and you'll see this:

![Tsuri Kichi Sanpei - Blue Marlin Hen-0](https://user-images.githubusercontent.com/7338867/136698368-4eb59d16-74f1-4082-8c7a-f7ffc967b7b4.png)

But you should really see this:

![Tsuri Kichi Sanpei - Blue Marlin Hen-02](https://user-images.githubusercontent.com/7338867/136698371-579ba0db-e045-4c6d-8dea-c16151507bb2.jpg)

**Comment by negativeExponent** [comment]
game works fine on my end... bad headered rom perhaps?

**Comment by ReyVGM** [comment]
It's no-intro. 

This was confirmed not be working correctly 4 months ago:
https://tasvideos.org/Forum/Topics/22851

It's possible it has since been fixed, I haven't checked.

**Comment by negativeExponent** [comment]
no-intro or not, most if not all NES rom verification does not check headers, only crc for PRG + CHR

**Comment by ReyVGM** [comment]
Doesn't matter now, it was already confirmed it was not working correctly. If it works for you, either you're using the [p1] version of the rom, or it has since been fixed by someone.

**Comment by negativeExponent** [comment]
no-into verified romsets do not use rom name indications such as [p1] in their file naming...

**Comment by ReyVGM** [comment]
Yep, I know [p1] is a GoodNES nomenclature. I'm just going by what was reported on the thread I posted. 

So I don't know what the problem is then, if you and I both have the same no-intro rom and are using the latest FCEUX 2.6.1 version, then why does it look fine for you and not me? Are you enabling a specific option or do you have a special dev version of FCEUX?

**Comment by mjbudd77** [comment]
There was a fix for VRAM size calculation in release 2.6.2. Have you tried this version?

**Comment by negativeExponent** [comment]
As stated on the forum you posted, u have a bad name table mirroring which is set by the header,..  it's has nothing to do if you have verified no intro or Goodnes sets. Fceux relies on correct header to play most of the know ROM.dumps. only a handful is added on database as required.

**Comment by ReyVGM** [comment]
> There was a fix for VRAM size calculation in release 2.6.2. Have you tried this version?

Yep, that's the one I'm using.


> As stated on the forum you posted, u have a bad name table mirroring which is set by the header,.. it's has nothing to do if you have verified no intro or Goodnes sets. Fceux relies on correct header to play most of the know ROM.dumps. only a handful is added on database as required.

Hmm, so how do I fix that? I assumed no-intro NES dumps had _no headers_, or am I wrong about that?

**Comment by negativeExponent** [comment]
Just fix your headers. Fceux has its own iNeS header editor you can use for that. See my screenshot to compare and see  what box to check

**Comment by ReyVGM** [comment]
Ok, I did it, thanks! Why was this happening on my end? I mean, I know now the header was wrong, but _why_ was it wrong? Aren't no-intro sets supposed to be "accurate"?

I guess this should be closed then since it's not really an emulation issue?

**Comment by LodanZark** [comment]
> Ok, I did it, thanks! Why was this happening on my end? I mean, I know now the header was wrong, but _why_ was it wrong? Aren't no-intro sets supposed to be "accurate"?
> 
> I guess this should be closed then since it's not really an emulation issue?

You can use this python script to fix your ROM headers
[NES2.0-Headers-Fixer.zip](https://github.com/TASEmulators/fceux/files/8036814/NES2.0-Headers-Fixer.zip)
:

**Comment by ReyVGM** [comment]
> > Ok, I did it, thanks! Why was this happening on my end? I mean, I know now the header was wrong, but _why_ was it wrong? Aren't no-intro sets supposed to be "accurate"?
> > I guess this should be closed then since it's not really an emulation issue?
> 
> You can use this python script to fix your ROM headers [NES2.0-Headers-Fixer.zip](https://github.com/TASEmulators/fceux/files/8036814/NES2.0-Headers-Fixer.zip) :

Thanks!

**Comment by negativeExponent** [comment]
No-intro and possibly other room verifiers only check the ROM data (prg and chr data) and skip the headers. Randomly getting a 'nointro' rompack or any packs does not guarantee headers to be correct

**Comment by ReyVGM** [comment]
Got it. Thanks for the info.
