### ISSUE TITLE
Screenshot colors different from the game itself

### ISSUE THREAD

**Issue by AkaZinion** [TASVideos/fceux#411]
Oops good morning, I wanted to report about something strange that is happening with my screenshots, their colors are different from the game itself, as you can see below.
![Megaman4-10](https://user-images.githubusercontent.com/92627788/137583289-8a9a6ff2-ee3c-41e2-949e-cf81978c5e94.png)
I ended up discovering that it was one of the special filters specifically the: hq2x, hq3x, that were doing this, if you can solve this in the next update I would appreciate it. Have a good day!

**Comment by mjbudd77** [comment]
This problem appears to only be with the older win32 version (I was able to reproduce it). I also tried this on the Qt version in Linux and everything looks fine. The Qt version also runs on windows. You may want to give it a try. It is the Win64 Qt/SDL (qfceux64.zip) download from the fceux website.

**Comment by AkaZinion** [comment]
Thanks! the Win64 Qt/SDL version didn't really happen the problem I was having before.
