### ISSUE TITLE
Load State incorrect when used during debugger breakpoint

### ISSUE THREAD

**Issue by Dwedit** [TASVideos/fceux#42]
If you Load State while the emulator is paused due to a debug breakpoint, or using the Step command, the CPU Cycles displayed in the debugger and PPU position will be incorrect after the state is loaded, leading to incorrect behavior once the game resumes.

Old PPU immediately displays the scanline number that it was at when the state was loaded.

New PPU behaves slightly differently, it will display the correct scanline in the debugger right after the state is loaded, but will change to the wrong scanline once enough cycles have passed.

Edit: More specifically, it's not related to debugging, just related to loading state at a timestamp different than the beginning of a frame.  The debugger is the usually way to get to a different timestamp.

**Comment by zeromus** [comment]
fceux will probably never support states mid-frame. it requires re-entering a loop midway after loading the state. It's impossible without the core emulation being designed that way from day one, and fceux is a long way from day one. I'm sure there are bugs about this on SF too. About all I could offer you is a lock-out from making savestates at inappropriate times (but it isn't clear how you could get to the perfectly appropriate time)
