### ISSUE TITLE
defaultconfig setup is confusing

### ISSUE THREAD

**Issue by bbbradsmith** [TASVideos/fceux#5]
Tried a clone and build for the first time since the migration to Git, and I ran into some problems (Windows).

1. Will not build until there is an scmrev.h in the vc/defaultconfig folder.

I discovered the make_scmrev.js script. When first running it, it crashed because I did not have a global install of Git in my path. After installing Git, I tried running it again, but it crashed again because I was running it from the wrong folder. Eventually discovered I had to run it from vc/ not from vc/defaultconfig/. After going through all these steps I was able to build FCEUX.

Could we maybe have a default scmrev.h already in the repository? Having to install Git globally (or at least manually creating a path for it) seems a very siginficant requirement for what looks like an unnecessary feature for anyone not trying to produce a public build with a revision stamp on it.

2. The build step runs BizHawk.Built.Tool.Exe which will crash because vc/svnrev_template.h is missing.

As far as I can tell, the result of this tool produces vc/svnrev.h which is not required by the build. The crash does not cause the build to fail, but produces a popup window with an error and some spam in the output on every build.

I was able to suppress the crash by copying svnrev_template.h over from a previous SVN repo I had on my hard drive, but it seems like this is a vestigial thing that has no function anyway? Should it be removed from the build step so it doesn't get in the way when it fails?

After addressing these two problems I was up and running. I  tried to find documentation that might explain what to do early on but couldn't find any. (Previously with SVN I was always able to just download and build with no additional setup.) Not sure if this would need documentation if svmrev.h had a fallback, and if svnrev_template.h wasn't really required at all though.

**Comment by vadosnaprimer** [comment]
This may help.
https://github.com/TASVideos/gens-rerecording/issues/117

But yeah, having revision 0 when no git is around sounds nice.

**Comment by bbbradsmith** [comment]
Should probably have also specified that I'm using the VC 2010 solution. Not sure if the build steps are set up differently for the 2014 version one (don't have 2014 installed currently).

**Comment by bbbradsmith** [comment]
Resolved by these two commits:
f0819b988c7c2775716bf1b8b768ee7c7e626a58
fd29f48d01b1480bd436be0ab84f2969707d20bb
