### ISSUE TITLE
#51 new feature breaks Linux compilation

### ISSUE THREAD

**Issue by noabody** [TASVideos/fceux#52]
#51 added features that don't exist in the SDL?.  I think the FCEUFILE* FCEUD_OpenArchive defines that were added to src\drivers\win\archive.cpp belong in src\drivers\sdl\sdl.cpp.  That resolves my FCEUD_OpenArchiveIndex undefined compilation error but then I get errors in driver.h where candidate expects 3 arguments but 5 are provided.

```
src/file.o: In function `FCEU_fopen(char const*, char const*, char*, char*, int, char const**, bool*)':
file.cpp:(.text+0x3513): undefined reference to `FCEUD_OpenArchiveIndex(ArchiveScanRecord&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, int, bool*)'
file.cpp:(.text+0x3bb5): undefined reference to `FCEUD_OpenArchive(ArchiveScanRecord&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*)'
file.cpp:(.text+0x3c01): undefined reference to `FCEUD_OpenArchive(ArchiveScanRecord&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >&, std::__cxx11::basic_string<char, std::char_traits<char>, std::allocator<char> >*, bool*)'
```

**Comment by owomomo** [comment]
I forgot the add the implement to the sdl version, though it only returns 0. You can test if it was fixed and post details if it still has errors.

**Comment by noabody** [comment]
Compile is perfect now.  Thank you so much!  It must be a tremendous pain to work with multi-platform code like this.  I wish I could do more than identify issues.

**Comment by jaygarcia** [comment]
@noabody please close this issue when you have a moment :).
