### ISSUE TITLE
Build fails in linux "AskSaveCheat" was not declared in this scope

### ISSUE THREAD

**Issue by gauauu** [TASVideos/fceux#60]
Building on ubuntu 18.04, witih g++, after commit fb1d489cfaabe19789d0444704b81e55ec7d2fc4 I get the following error when running scons.

```
src/fceu.cpp: In function 'void FCEU_CloseGame()':
src/fceu.cpp:195:5: error: 'AskSaveCheat' was not declared in this scope
     AskSaveCheat();
     ^~~~~~~~~~~~
src/fceu.cpp:195:5: note: suggested alternative: 'savecheats'
     AskSaveCheat();
     ^~~~~~~~~~~~
     savecheats
```

**Comment by gauauu** [comment]
Looking at it a little more carefully this morning, it looks like AskSaveCheat is only defined for the windows build (in drivers/win/cheap.h/cpp), so this probably needs to be wrapped in an IFDEF, something like 
```
		if (GameInfo->type != GIT_NSF) {
			if (disableAutoLSCheats == 2)
				FCEU_FlushGameCheats(0, 1);
#ifdef WIN32
			else if (disableAutoLSCheats == 1)
				AskSaveCheat();
#endif
			else if (disableAutoLSCheats == 0)
				FCEU_FlushGameCheats(0, 0);
		}
```
I could submit a PR with that sort of change, but I'm not extremely familiar with this codebase, so I'm more inclined to let somebody who knows the history of this change take a look at it.

Thanks!

**Comment by bbbradsmith** [comment]
As a related thought, would it be worth adding a Linux configuration to the appveyor build?
