### ISSUE TITLE
Integer overflow in sound config module

### ISSUE THREAD

**Issue by secnotes** [TASVideos/fceux#603]
Although fceux limits the range of parameters via the GUI, the cmd/shell does not filter illegal parameters.

```shell
$ ./fceux --soundrate 2000 --soundbufsize 4200000 ./z___game_006.nes
/home/lys/fceux/src/drivers/Qt/sdl-sound.cpp:234:30: runtime error: signed integer overflow: 4200000 * 2000 cannot be represented in type 'int'
```

```shell
$ ./fceux --soundrate 10 ./z___game_006.nes 
/home/lys/fceux/src/filter.cpp:68:20: runtime error: signed integer overflow: -42426476475531 * 616038 cannot be represented in type 'long long int'
/home/lys/fceux/src/filter.cpp:69:25: runtime error: signed integer overflow: 197082212775433 * 157286 cannot be represented in type 'long long int'
```

Of course, this problem only makes fceux unresponsive. I just want to explain whether it is necessary to unify the parameter range of cmd and GUI. Anyway, this is an excellent nes emulator!

Thank you for your outstanding work, which made our meeting a childhood :)

**Comment by thor2016** [comment]
Fixed in commit 37bf5c9
