### ISSUE TITLE
Report bug: An error occurred while running some games in 168-in-1.

### ISSUE THREAD

**Issue by a65090482** [TASVideos/fceux#68]
When I use the latest version of Virtua NES to run the B-Wings game in 168-in-1 (including B-Wings SID, etc.), there is no exception, but when I use the latest version of fceux to run it, it only shows the background and only plays BGM all the time.

PS: Non-manual translation.
[168-in-1.zip](https://github.com/TASVideos/fceux/files/3415393/168-in-1.zip)

**Comment by g0me3** [comment]
fixed a3d4db6b1a0617c83445b1eb7c43dcf3f2d714a7

**Comment by g0me3** [comment]
lol this fix actually breaks the chinese rpg games support by waixing, since they uses similar mapper but does not want a write protection lol

**Comment by g0me3** [comment]
refix 1f5ce9e120fa3691f3cf0d40e594341dba843222

i think nesdev is wrong about write prot bits or even they uses a different mappers either on multigame carts or waixing single game variants

if anybody have both kind of carts with mapper 227 pass them to me and I can verify it on the hardware.
