### ISSUE TITLE
Hotkey menu crashes in 32-bit Linux Mint

### ISSUE THREAD

**Issue by PalomBM** [TASVideos/fceux#69]
Clicking on the Hotkeys window crashes the emulator, making it exit the compiled source or freezing the 2.2.2 version in Software Manager.

**Comment by mjbudd77** [comment]
I believe I have a fix for this issue as part of a rather large merge request. I do not know when this merge request will be accepted. If you want to try out some of my new feature updates for the Linux GUI, clone/build my fork of this project mjbudd77/fceux.

**Comment by mjbudd77** [comment]
This is now fixed in the master branch
