### ISSUE TITLE
Mapper 15 CHR-RAM write protection

### ISSUE THREAD

**Issue by norill** [TASVideos/fceux#76]
CHR-RAM should be write-protected on this board in bank modes 0 and 3

[http://wiki.nesdev.com/w/index.php/INES_Mapper_015#Control_.28.248000-.24FFFF.29]()

**Comment by norill** [comment]
perhaps related  #68

**Comment by g0me3** [comment]
are there any games with problems caused by lack of chr write protection? i can add this feature, but you won't see the difference if there are no such problems.

**Comment by norill** [comment]
sorry, i should have given this info in the first comment. an example is Contra 168 in 1 (CRC 9BBF3E5D) - title screen game 20 - Urban Champion has garbled tiles

**Comment by g0me3** [comment]
fixed in 8b1c405d95df1b831de73b1c71c238eddadfa720
