### ISSUE TITLE
Jackal NES - wrong value in trace logger for ROM value and A reg

### ISSUE THREAD

**Issue by guitarmaestro69** [TASVideos/fceux#78]
Beginning of Level 3, Jackal NES, $907C reads as $20 in the trace logger, but it is really $B0.  stepping through confirms this, as well mesen's output is correct.
![jreh](https://user-images.githubusercontent.com/30304768/66881772-f456b700-ef95-11e9-88f0-46f75ee8ac28.png)

**Comment by g0me3** [comment]
can't reproduce it here. all working just fine as intended for me.
https://www.dropbox.com/s/w9eayxzitaiqvs9/Image1.png?dl=0
are you sure you have not cheats enabled or another lua/handler modifiers?

**Comment by g0me3** [comment]
disassembly routines for debugging window and for trace logger are the same. if there were had any bug with memory mapping... but there are no any $20 at the same address in whole ROM...

**Comment by guitarmaestro69** [comment]
i dont use lua
never turned on cheats
ill try to reproduce it myself
________________________________

**Comment by guitarmaestro69** [comment]
very strange indeed.  i cannot reproduce it either.
