### ISSUE TITLE
Multiline comments issue

### ISSUE THREAD

**Issue by cyneprepou4uk** [TASVideos/fceux#88]
Adding multiline comments via .nl file messes up text color below, and the first symbol doesn't appear in lower lines. I'm using latest build.

![Снимок](https://user-images.githubusercontent.com/59050458/71702617-904bce00-2de1-11ea-88ee-429613c29bb2.PNG)

**Comment by cyneprepou4uk** [comment]
First symbol starts to disapear in [r3309](https://sourceforge.net/p/fceultra/code/3309/).

Can't say precisely when colors began to mess up, because colors they were gradually added from [r3310 to r3319](https://sourceforge.net/p/fceultra/code/3319/log/). Maybe in r3317, this is where opcodes began to have blue color

![Снимок1](https://user-images.githubusercontent.com/59050458/72218530-ae859c80-354c-11ea-9870-069732f268fc.PNG)

**Comment by owomomo** [comment]
The debugger seems have some ambiguous with line feed between `\r\n` and `\n`. I've solved this problem by assuming all the line feeds are `\r\n`.

**Comment by vadosnaprimer** [comment]
Thanks.
