### ISSUE TITLE
An enabled breakpoint forbits execution of another breakpoints when its conditions are not met

### ISSUE THREAD

**Issue by cyneprepou4uk** [TASVideos/fceux#90]
It started from [r3362](https://sourceforge.net/p/fceultra/code/3362/). And I'm not talking about Forbit breakpoints.

A breakpoint blocks triggers of other breakpoints if all these are true:
1 - it is located above them in the list
2 - it is enabled
3 - its condition is not met
4 - its triggering CPU address includes an address where breakpoint below should trigger

An example:
I have a test ROM which loops infinitely in $8000-$FFF7 range.
[dummy.zip](https://github.com/TASVideos/fceux/files/4050505/dummy.zip)

At $8010 I add an LDA $0100 instruction.
Then I add an Execute breakpoint for $8000-$8100 range with A==#10 condition. This breakpoint never triggers because its condition never meets.
Then I add a Read breakpoint for $0100. 
![Снимок](https://user-images.githubusercontent.com/59050458/72217369-d28db180-353d-11ea-9a0a-665606a1c210.PNG)

Read breakpoint should trigger all the time because of the infinite loop, however that Execute breakpoint blocks the trigger while being enabled. If I disable Execute, then Read breakpoint triggers normally.

In versions older then r3362, there could be several triggers on the same instruction at the same time, for example if you add 2 Read breakpoints for $0100 and press Run after 1st triggers, then the 2nd one also pauses emulator instead of moving on with emulation.

Starting from r3362, only 1 beakpoint can be triggered at a time. I actually don't know which one is better. When several can be triggered, it shows you which one from the list have their condition met, but it can be annoying sometimes as well.

Also, [r3363](https://sourceforge.net/p/fceultra/code/3363/) contains an additional bugfix for 790 issue. I can't say if it important for my current issue (because I'm not a programmer), like will it still keep working independently if you revert r3362 or something, so check it out.

**Comment by g0me3** [comment]
Work as it should be for me with your ROM. see highlighted option in the breakpoints list triggered as you expected.
https://www.dropbox.com/s/f0fat9cqz9ezxp5/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202020-01-12%2015.50.13.png?dl=0
look if you did something special with your cheats/scripts/handlers or something else. current revision does not have this problem.

**Comment by cyneprepou4uk** [comment]
> Work as it should be for me with your ROM.
https://www.dropbox.com/s/f0fat9cqz9ezxp5/%D0%A1%D0%BA%D1%80%D0%B8%D0%BD%D1%88%D0%BE%D1%82%202020-01-12%2015.50.13.png?dl=0

**Comment by cyneprepou4uk** [comment]
oops, pressed wrong button.

Anyway, your execute breakpoint is $8000-$8010, which doesn't include $8100, where you wrote LDA.

Try again

**Comment by g0me3** [comment]
then yes

**Comment by g0me3** [comment]
fixed in db003f841d8d1f512e80194d0d3b6bf7b456fb77
