### ISSUE TITLE
Subtitles converting

### ISSUE THREAD

**Issue by anonymous7002** [TASVideos/fceux#92]
How can I convert .fm2 file subtitles to a .srt file that could be toggled easily?
.fm2 subtitles look like this:
subtitle 13000 I'm fond of the color-a-dinosaur running gag
subtitle 13300 So it was obligatory for this run
subtitle 13600 Human can use controller to color realtime

**Comment by anonymous7002** [comment]
By the way, how long the subtitles stay on the screen?

**Comment by bbbradsmith** [comment]
My guess is 400 frames? (6.6s)

https://github.com/TASVideos/fceux/blob/d292d333286ae7ed001dc25889a0bab2751ac36b/src/movie.cpp#L2011

What is the question though? You seen to understand .FM2's subtitle format. I assume you know how the .SRT format works. What do you need to know?
