### ISSUE TITLE
Releases

### ISSUE THREAD

**Issue by dellelce** [TASVideos/fceux#93]
There have been no new releases since 2.2.2 while there are over 600 commits.

Any plan to push new releases (or just tags..)?

Thanks

**Comment by keithbowes** [comment]
[The website](http://fceux.com) says that the latest version is 2.2.3.  It's beyond me why that tag isn't available on Github.

**Comment by bbbradsmith** [comment]
2.2.3 predates the transition to GitHub. If you want to find the commit in the history though I could probably tag it for you.

**Comment by bbbradsmith** [comment]
It seems I do have permission after all, just not in my git client, only on the website? I dunno. I created a release for 2.2.3:

https://github.com/TASVideos/fceux/releases/tag/fceux-2.2.3

**Comment by LodanZark** [comment]
I'm a bit confused, 2.2.3 was released at 28 July 2016, the one available in this repo it's the same version or it's upstream?

**Comment by bbbradsmith** [comment]
It's just a link to the sourceforge release.

**Comment by LodanZark** [comment]
Are there any plans to release 2.2.4 in the future?

**Comment by bbbradsmith** [comment]
Unsure, but you can always try the latest changes from the automated build:
https://ci.appveyor.com/project/zeromus/fceux/build/artifacts

**Comment by CameronNemo** [comment]
Most linux distros will not distribute from a git commit, they need a release tagged. I would recommend making a release sometime to capture the more recent changes.

**Comment by mjbudd77** [comment]
I agree that a new release should occur in the near future. At the moment I am still porting the debug features into the Qt/SDL version and double checking that the changes I have been making are stable. I do not get much feedback from other Linux users and would like to hear how the application runs on various Linux distros.  I am currently doing all my development and testing in CentOS8. Getting some feedback would go a long way in helping me determine whether this code is release ready.

**Comment by jnahmias** [comment]
Hello,
I am the original Debian packager of fceu(x). I am getting back into Debian in general and would be happy to test, give advice, and package up the latest release. I will start by updating the package in Debian to the 2.2.3 release (it's still on 2.2.2). I also set up notifications so that I am alerted when a new version is tagged here so I can package it. Happy to test stuff in the meantime.
--Joe

**Comment by mjbudd77** [comment]
Hi Joe,  I appreciate the help. You will find that the latest code is quite different than what is on the 2.2.3 release. Be sure to read the README and TODO.SDL files as I have put a lot of helpful notes in there. Also, I have a couple scripts that are building and packaging fceux in the Ubuntu 20 appveyor environment. You can find those scripts in the pipelines folder.

**Comment by svein83** [comment]
Are there build instructions with requirements available? I would do some testing in Arch if could get it built and installed.

**Comment by mjbudd77** [comment]
Yes, all build instructions are in the project README file.

**Comment by zeromus** [comment]
OK, presto, you have a new release.

**Comment by mjbudd77** [comment]
@jnahmias , are you still onboard with packaging this new release for
Debian Linux now that it is ready? Let me know if you want help.
