### ISSUE TITLE
Suggestion: Have graphical output centered in window

### ISSUE THREAD

**Issue by shentino** [TASVideos/fceux#99]
If the window is bigger than the output, center the output inside the window.

**Comment by mjbudd77** [comment]
The SDL port does this.

**Comment by shentino** [comment]
What about GL?

**Comment by mjbudd77** [comment]
The Qt/SDL port uses OpenGL by default. However this port is only targeted towards Linux and Mac OSX.

**Comment by shentino** [comment]
I'm using fceux 2.2.3 on gentoo linux, are all of their ports supposed to be centered?

also by "this port" do you mean that different platforms get handled differently on this issue?

**Comment by mjbudd77** [comment]
The gui front end for Linux and Mac OS was completely rewritten this year. The new code has not yet been released and you can only get it from this git repo. To use it, you will have clone this repo and build it from source. Build instructions are in the projects README file. What I mean by this port, is that this version uses a completely different front end than the windows OS based version. Although both use the same common emulation core, the Linux/Mac version uses cross platform Qt and SDL libraries. So give the new Qt/SDL version of fceux a try.

**Comment by shentino** [comment]
Works for now at least on qt
